### ISSUE TITLE
create worker from data uri may throw security error in Chrome

### ISSUE THREAD

**Issue by daiheitan** [andywer/threads.js#10]
Check: http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string

Maybe using `blob` or some library would be a better solution

**Comment by tchakabam** [comment]
See here for some workarounds: https://code.google.com/p/chromium/issues/detail?id=357664

For example this polyfill does it for my case: https://github.com/Rob--W/chrome-api/blob/master/patch-worker/patch-worker.js

**Comment by daiheitan** [comment]
I don know why but the author of this module do not reply to my issues any more. So I forked thread.js and solved them... Anyway thanks.

**Comment by andywer** [comment]
Sorry folks, I lost focus on the thing while having a lot of other stuff to do.

@tchakabam Tried to avoid another polyfill, but apparently the Blob API does more than just the one-liner I used. I will create a new branch with this polyfill for testing.

@daiheitan I looked at the commit in your fork. Can you tell me how you use your `.require()`? `require` sounds commonjs-ish to me, but it's `this[name] = Function.apply(null, method.args.concat(method.body))`.

Anyway thanks a lot for your effort!

**Comment by daiheitan** [comment]
@andywer `require()` is just a syntax I borrowed from another web worker module. My commit is just a quick fix rather than a mature idea. So let's just talk about the issues, not my code XD

**Comment by tchakabam** [comment]
Thanks for the reply! :)

**Comment by andywer** [comment]
@daiheitan @tchakabam Is this fixed by now? There was a commit for more thoughtful data URI creation that made it's way into 0.5.4. I am sorry for the few time I have for this library right now... :-/

**Comment by daiheitan** [comment]
@andywer Sorry I switched to webpack for workers after a few tries with this lib. But I think the problem is fixed by the newest version.

**Comment by andywer** [comment]
@daiheitan Thanks for your quick response!
