### ISSUE TITLE
Use async/await inside of run method

### ISSUE THREAD

**Issue by Neuroforge** [andywer/threads.js#101]
I am having problems creating a background worker that can call await/async functions.

I have an AngularJs project which i would like to add a background worker to.

If i create a worker like so, it works well and as expected.

	this.worker = spawn(function() {});
		this.worker
			.run(function(input, done, progress) {
				let files = input.data.fileList;
				for (var i = 0; i < files.length; i++) {
					var g = 0;
					while (g < 1000000000) {
						g++;
					}
					
					progress({ currentIndex: i + 1, totalFiles: files.length });
				}
				done(parentDirectory);
			})
			.on('progress', function(update) {
				that.uploadedFileUpdateCallback(update.currentIndex, update.totalFiles);
				console.log(update);
			})
			// The handlers come here: (none of them is mandatory)
			.on('message', function(response) {
				console.log(response);
				that.uploadedFileCompleteCallback(response);
			})
			.on('error', function(error) {
				console.error('Worker errored:', error);
			})
			.on('exit', function() {
				console.log('Worker has been terminated.');
			})
			.send({ data: input });

This is what i have tried but i get a strange "Uncaught ReferenceError: tslib__WEBPACK_IMPORTED_MODULE_0__ is not defined" error

		this.worker = spawn(function() {});
		this.worker
			.run(async function(input, done, progress) {
				let files = input.data.fileList;
				for (var i = 0; i < files.length; i++) {

					await cornerstonejs.loadImage(file);
				}
				done(parentDirectory);
			})
			.on('progress', async function(update) {
				that.uploadedFileUpdateCallback(update.currentIndex, update.totalFiles);
				console.log(update);
			})
			// The handlers come here: (none of them is mandatory)
			.on('message', async function(response) {
				console.log(response);
				that.uploadedFileCompleteCallback(response);
			})
			.on('error', function(error) {
				console.error('Worker errored:', error);
			})
			.on('exit', function() {
				console.log('Worker has been terminated.');
			})
			.send({ data: input });

Any tips or advise on this? The file type and associated library only have an API method that I can use which returns a promise. How to resolve promises in the background thread?

**Comment by andywer** [comment]
Hey @Neuroforge!

Looks like it's due to `cornerstonejs` being defined/imported outside the function that you are running in the worker context.

I can only highly recommend waiting for v1.0 (see #100) for the time being. It will come with a completely new API that is hopefully much clearer and you won't have to deal with these kind of limitations anymore. Feel free to check it out and leave some feedback if you want :)

Sorry that I can't provide an elegant solution that works for you in this moment 😉
