### ISSUE TITLE
v1 Using function imported from a file that has expose locks up script

### ISSUE THREAD

**Issue by aarmora** [andywer/threads.js#109]
If you try to export a function that is also using `expose` the script will just hang.

See in the image attached. In `looper.ts` the function `pizza()` is being exported. If it's called in `index.ts` the script will just hang when you try to run it. I didn't ever wait for it to crash so I'm not sure the error but no part of the script runs as far as I can tell.

Maybe this is expected and if so, this can be disregarded and just addressed via documentation.

#100 

![image](https://user-images.githubusercontent.com/6865538/59154350-f0d28280-8a2d-11e9-8859-9dacee42d7d2.png)

**Comment by andywer** [comment]
#111 just introduced an explicit error with a clear error message in case you call `expose()` from the main thread.

Hope that solves the issue for you.
