### ISSUE TITLE
module 'threads' not found when used in browser

### ISSUE THREAD

**Issue by pheyvaer** [andywer/threads.js#13]
When follow the 'basic usage' example to test this module in the browser. I get the error that the module 'threads' is not found. I installed the module using Bower and included it using `<script>`. Is there something else I need to do to make it available?

**Comment by andywer** [comment]
Ahh, I just saw that it's called `winodw.thread` (singular) when not used as a CommonJS or AMD module. I am just afraid to change it to plural, since that could cause existing implementations to break... :-/
