### ISSUE TITLE
MongoId converted to bson when passed in to pool spawn

### ISSUE THREAD

**Issue by aarmora** [andywer/threads.js#143]
I'm passing an object to a worker that is in a pool queue. The object has a mongoId (example: `_id: 5d47967841aad852104fdb0e`. Before it goes in it looks great. When it hits the worker function, it's somehow converted to bson.

I was calling this function just normal (without any threads or pools) previously and the information passed as I would have expected.

![image](https://user-images.githubusercontent.com/6865538/62622598-f3d9da00-b8db-11e9-92f4-fac2c5331b64.png)
![image](https://user-images.githubusercontent.com/6865538/62622610-ffc59c00-b8db-11e9-8956-002aa57d6de2.png)

```
// File with pool
const pool = Pool(() => spawn(new Worker("./workers/checkStatusWorker")), 8 /* optional size */)

console.log('passing in lead', lead);
pool.queue(async checkStatus => checkStatus(lead));
```

```
// checkStatusWorker
expose(async function checkStatus(lead: ILead) {
	console.log('received lead', lead);
```

**Comment by andywer** [comment]
Yeah, I suppose the `MongoId` comes with a separate `toString()` and `toJSON()` method. So when it's `JSON.stringify()`-ed it gets serialized to something else then what you see when you log it.

See also #141.

**Comment by andywer** [comment]
Closing. Feel free to re-open if there is more to be done, but I think the user has to handle those instances themselves as there's no way to serialize/deserialize them in a generic fashion.
