### ISSUE TITLE
OMG Thank you

### ISSUE THREAD

**Issue by loganpowell** [andywer/threads.js#146]
I've tried `workerpool`, `worker`, and `workaway`. None of them worked as expected across node and the browser....

Until I tried `threads`. Well I had to try twice (once with webpack to no avail and then with parcel **SUCCESS**)

Thank you so much for this library. It's amazing.

**Comment by andywer** [comment]
Thanks, Logan! I appreciate it a lot 🙂

Since you tried a bunch of libs... Do you have any suggestions how the unique value of threads.js should be communicated, in the readme, for instance?

**Comment by andywer** [comment]
PS: If you don’t mind... What was the issue with webpack?

**Comment by loganpowell** [comment]
I'm not actually sure what the issue is with webpack. It's probably because it super complex and there are a million ways to use it (of which I'm familiar with about one). The parcel setup was super straightforward - given your helper `import "threads/register"`

Here's my experience:
1. None of the other libraries seem to have actually been designed for cross-platform use, it seems to me that your implementation put that as a top priority (so for people looking for cross-platform that should be a huge selling point)
2. `threads`' API is very straight forward/well designed/thoroughly considered. I found it more ergonomic than the others as well, perhaps that might have also contributed to my inability to make the others work across node and the browser
3. I got `workerpool` working in node, but not in the browser. Then I got `workaway` working in the browser, but not in node ( i think because that one relies on explicit use of `importScripts`), which your API abstracts away (thank god)
4. I didn't run any benchmarks, but I get the feeling that your implementation was also faster than the others. I don't exactly know why, but I do know that `workerpool` does some internal webpack'ing to get a script inlined into a worker (but `workerpool` is also trying to include node 12's `worker threads` api as well), 
5. I think the fact that you have a laser focus on what your library is trying to accomplish: make it *easier* to use multiple processes  *across platforms* in a *very seemless fashion*. 
6. Ergonomics
7. Ergonomics
8. Ergonomics

💯

**Comment by loganpowell** [comment]
Dude, it somehow slipped my mind that threads also abstracts over `worker threads` in node 12! I'm sorry!!

Btw, I'd like to help you promote threads. Is there a fund I can contribute to?

**Comment by loganpowell** [comment]
Oh, one more *huge* deal about `threads` you don't have in your landing page is that you can use `require` in them!

**Comment by loganpowell** [comment]
I'm sorry I keep pinging this closed issue, but I will be out of your hair soon, when the excitement wanes...

One of the reasons `workerpool` has such great npm stats is that it's used in a build tool used in this ember tutorial starter project:

https://guides.emberjs.com/release/tutorial/

here's the build tool's package.json

https://github.com/babel/broccoli-babel-transpiler/blob/master/package.json

**Comment by andywer** [comment]
No, keep going, it's fine. This is the kind of stuff I enjoy reading in issues 😉😄

> I'd like to help you promote threads

Great!

> Is there a fund I can contribute to?

Still on the GitHub sponsors waiting list... I could start accepting crypto, though. Maybe I should add a donation page to the website, with crypto account addresses and QR codes.

**Comment by loganpowell** [comment]
If you add a donation button, just make it small... ;) I'd be happy to donate

**Comment by loganpowell** [comment]
I can also venmo you...

**Comment by andywer** [comment]
> If you add a donation button, just make it small... ;)

Will do 😄😄

> I can also venmo you

You can only use venmo with a US bank account and phone number. So that's unfortunately a *won't fix* for me...

PayPal would work, I guess.

**Comment by loganpowell** [comment]
paypal works for me

**Comment by loganpowell** [comment]
can you DM me your paypal info or you can leave it here if that works for you

**Comment by andywer** [comment]
I already did. DM-ed you on Twitter 😉
