### ISSUE TITLE
Browser: Uncaught TypeError: process.on is not a function

### ISSUE THREAD

**Issue by lsavage92** [andywer/threads.js#148]
I was using `v0.12.0` for use in the browser and it was working but after upgrading I get an error that says `Uncaught TypeError: process.on is not a function`. This error seems to be thrown by simply doing:

`import { Pool } from 'threads'`

I'm using Chrome `Version 76.0.3809.100`, threads `v1.0.0-beta.3`, node `v9.10.0`

**Comment by Luiz-N** [comment]
seeing this issue as well

**Comment by andywer** [comment]
Thanks for reporting!

What bundler are you using? Or are you using any at all?

**Comment by lsavage92** [comment]
I am using webpack `^4.28.3` and the config is generated from vue-cli + a small amount of customization.

**Comment by andywer** [comment]
Thanks! I think I might have located the origin of the problem.

Try installing `threads@1.0.0-beta.3-bugfix-148` and see if the problem is fixed or not. If it still fails, it would be great if you could provide a stack trace.

**Comment by lsavage92** [comment]
Ahh! You are the best! The fix works perfectly. Thank you so much for the quick turnaround.

**Comment by andywer** [comment]
Will wait a little more and see if the fix for #147 works, too, and then release a new version.
