### ISSUE TITLE
No ability to set thread debug port -- or this is undocumented

### ISSUE THREAD

**Issue by ptschnack** [andywer/threads.js#16]
It would be handy to be able to configure the debug listener port used by child threads. Right now child threads attempt to use the same port as the parent thread causing EADDRINUSE exception to be thrown.

**Comment by andywer** [comment]
Good point. Any quick thoughts how to implement this? I am not aware of a way to change the debugger's port during runtime.

**Comment by ptschnack** [comment]
The important thing is to have each thread listen on a different port. As it stands now, you simply cannot fire off a new thread because it immediately throws an EADDRINUSE exception.

With child *processes* one gets around this so:


var child = require('child_process');
var debug = typeof v8debug === 'object';
if (debug) {   
    //Set an unused port number.    
    process.execArgv.push('--debug=' + (40894));    
}    


(E.g. see: http://stackoverflow.com/questions/16840623/how-to-debug-node-js-child-forked-process)

I don't know how this translates to your threads implementation if these are true threads and not child processes. Perhaps spawn and run could take an options parameter in which the debug port could be specified.

Thanks for thinking about this. If you fix this, I'd love to try it out. (Other threading packages have the same problem, so I've given up on threading for now.)

Paul S...


--------------------------------------------
On Wed, 5/25/16, Andy Wermke <notifications@github.com> wrote:

 Subject: Re: [andywer/threads.js] No ability to set thread debug port -- or this is undocumented (#16)
 To: "andywer/threads.js" <threads.js@noreply.github.com>
 Cc: "ptschnack" <ptschnack@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Wednesday, May 25, 2016, 10:25 AM
 
 Good point. Any quick thoughts
 how to implement this? I am not aware of a way to change the
 debugger's port during runtime.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by andywer** [comment]
Hey Paul. Try this branch: https://github.com/andywer/threads.js/tree/debugger-port-fix :)

Tell me if it works for you.

**Comment by ptschnack** [comment]
Hi, Andy,

Thanks for the prompt attention to this. 

Spawning a worker no longer crashes and running attached files from the command line generates expected output:

  prompt>  node app.js

  spawning worker
  spawned worker
  worker here!
  worker: {"0":{"do":"Something awesome!"}}
  worker.js replied: Awesome thread script may run in browser and node.js!


Now if only the output and thread could be debugged using Visual Studio nodejstools ... Output from the same files run inside Visual Studio 2015 Community (free!) with nodejstools on Windows 10:x64

  Debugger listening on port 5858
   spawning worker
  Debugger listening on port 45859
   spawned worker


Note that none of the console output from the worker is printed nor is console logging from the message listener output either. Most other node.js code is debuggable and under Visual Studio, so are they exposing debug ports in a way that threads isn't?

Again, thanks. I'll revisit using threads in my project if I can find a reasonable way to debug them.

Paul Schnackenberg


--------------------------------------------
On Fri, 5/27/16, Andy Wermke <notifications@github.com> wrote:

 Subject: Re: [andywer/threads.js] No ability to set thread debug port -- or this is undocumented (#16)
 To: "andywer/threads.js" <threads.js@noreply.github.com>
 Cc: "ptschnack" <ptschnack@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, May 27, 2016, 7:00 AM
 
 Hey Paul. Try this branch: https://github.com/andywer/threads.js/tree/debugger-port-fix
 :)
 
 Tell me if it works for you.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by andywer** [comment]
Fair enough. I already thought about this issue some time since you opened it.

Do you know another multi-threading library for node.js that provides better debugging capabilities? Maybe we can avoid re-inventing the wheel :)

**Comment by ptschnack** [comment]
Not that doesn't have the port collision problem. If I had run across such I would be using it and probably not have submitted the bug.

--------------------------------------------
On Tue, 5/31/16, Andy Wermke <notifications@github.com> wrote:

 Subject: Re: [andywer/threads.js] No ability to set thread debug port -- or this is undocumented (#16)
 To: "andywer/threads.js" <threads.js@noreply.github.com>
 Cc: "ptschnack" <ptschnack@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, May 31, 2016, 2:20 PM
 
 Fair enough. I already thought
 about this issue some time since you opened it.
 
 Do you know another multi-threading library for node.js
 that provides better debugging capabilities? Maybe we can
 avoid re-inventing the wheel :)
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by bigman73** [comment]
I'm running the ThreadPool node.js sample on Visual Studio Code and get the same EADDRINUSE

**Comment by curiouslybrown** [comment]
This is now broken again in Node v7 with the --inspect flag. If you use --inspect it actually crashes the workers. The ultimate fix would be to use --inspect=port, but I just set options.execArgv = []; for the fork and use it that way.

**Comment by andywer** [comment]
@curiouslybrown Could you provide a link to your `options.execArgv` fix or open a PR?

**Comment by scinos** [comment]
For anyone looking for a solution: this hack works for me

```
let PORT = 9229;
const getSpawnArgs = () => {
    if (process.execArgv.includes('--inspect')) return [`--inspect=${++PORT}`];
    return [];
};

const thread = spawn('worker.js'), {
    execArgv: getSpawnArgs(),
});
```

@andywer if you are happy with a solution like that (detect port used for `inspect` or `inspect-brk` and use incremental ports for each worker), let me know and I'll work an PR.

**Comment by andywer** [comment]
@scinos Cool! Sure, a PR would be much appreciated 👍

Just got to figure out why the tests keep failing recently...

**Comment by scinos** [comment]
Not sure if related, but for running the tests locally I had to change babel config to

```
  "babel": {
    "presets": [
      [
        "es2015",
        {
          "loose": true
        }
      ]
    ]
  },
```

**Comment by andywer** [comment]
@all Please have a look at #68 if you struggle with the issue and have a few minutes time. @scinos opened a PR with a very promising solution!

**Comment by andywer** [comment]
ℹ️ Update to `v0.10.0` to get the fix.
