### ISSUE TITLE
Process does not exit after Thread.terminate

### ISSUE THREAD

**Issue by kylestlb** [andywer/threads.js#162]
threads v 1.0.0-beta.6
tiny-worker v 2.2.0
node 10.14.1

Maybe I'm missing a big gotcha here, but I noticed this while trying to run some unit tests in a larger project.  Created a simple test to see if I could replicate behavior, and it turns out I could.  Switched to node 12 and no longer observed the issue.  Here's the code:

index.js:

```
const { spawn, Worker, Thread } = require('threads');

const f = async function() {
    const work = await spawn(new Worker('./test-worker'));
    const res = await work();
    await Thread.terminate(work);  
};

f().then(res => {
    console.log('done!');
});
```
test-worker.js:
```
const { expose } = require('threads');

expose(function() {
    return 'done';
});
```

run command:
`node index.js`

after running `node index.js` the process hangs and I have to kill from another terminal.  Running the same command with node 12 and the process exits.  Might it be due to some tiny-worker bug?

**Comment by yawetse** [comment]
@kylestlb thanks for the awesome library. Just noting that I ran into the same issue.

Thanks again

**Comment by andywer** [comment]
Hey guys!

Very much looks like an issue with `tiny-worker`, indeed. It's not documented, but node 10 is a bit of a special case as you can already use worker threads instead of tiny-worker, but only if you set a feature flag.

Just run your application with `node --experimental-worker` and threads.js should automatically use the native worker threads. Haven't tested it yet, but it's really straight forward.

I know it's not ideal, but it might just solve your issue for now 😉

**Comment by yawetse** [comment]
Thanks for the speedy response! It is indeed an issue with tiny-worker.

I think this issue is probably safe to be marked as closed.

Thanks again for the awesome module

**Comment by andywer** [comment]
I closed the issue already, but can you do me a favor?

Please run your program once more without the worker feature flag, so the tiny-worker polyfill is used again and add this code to your worker:

```js
process.on("disconnect", () => process.exit())
```

Tell me if it solves the issue. Unfortunately I really don't have the time this week to try it myself.

Will add the fix to threads.js and contribute back to tiny-worker if the fix works.

**Comment by yawetse** [comment]
Yes calling process.exit on the disconnect handler also works and terminated the process properly

**Comment by andywer** [comment]
Awesome – thanks for checking!

**Comment by andywer** [comment]
Re-opening until the fix is shipped.

**Comment by andywer** [comment]
Please update to [tiny-worker v2.3.0](https://github.com/avoidwork/tiny-worker/releases/tag/2.3.0). It was just released and contains the fix 🚀
