### ISSUE TITLE
Congrats, thanks and couple of questions / feedback

### ISSUE THREAD

**Issue by cancerberoSgx** [andywer/threads.js#163]

**Comment by cancerberoSgx** [comment]
This library is awesome - the way the API is designed makes this a piece of cake, Thanks!, 

My particular question is that if all the features listed in the docs are supported in node LTS (version 10) which unfortunately I need to support. Also to know if there is any relevant difference in performance between tiny-worker and the real thing in 12 ? and if so which aspect is implied (initialization, speed, memory? - that could help me minimizing bottlenecks if any/known)

Feedback: on each of the documentation (which is excellent) it would be nice if each section has a note about support regarding the platform's version. For example, when using transferable, just a little note at the end of the section saying "Transferables is part of version A of standard B, in Node.js are supported from version C. In browsers this is the current support (link to caniuse). This is just to clarify to newbies like me that some support depends on the platform.

Also a doubt/feedback I have is  regarding ts-node (which I use daily) but gives me the impression you are actually encouraging users and I suspect it has considerable impact on performance (for sure I wouldn't use it in production even if you spawn it with `-T`) . I don't think this only impacts on worker initialization but overall. - and I suspect not only on initialization but on calls too.

I will try to contribute with a little guide using parcel which makes it trivial to run **the same** code  in node and browsers with zero config and whit a little more research contribute with the little clarifications I mentioned. 
Thanks again  and sorry for the non important questions /feedback here but I'm was fighting with several workes/cluster/ipc spaghetti projects and I'm glad to see this! :) thanks!

**Comment by andywer** [comment]
Hey @cancerberoSgx.

Thank you! Always happy to see that people can make good use of it. Unfortunately I really don't have any time to go into any details now, but the documentation should cover this - agreed 👍

I just pointed out in a different issue how to use threads.js without the tiny-worker polyfill in node 10. Maybe this is already good enough for now: https://github.com/andywer/threads.js/issues/162#issuecomment-533103307

**Comment by cancerberoSgx** [comment]
@andywer Thanks that saved my day since I was blocked by this problem: https://github.com/avoidwork/tiny-worker/issues/34  Thanks!
