### ISSUE TITLE
Error: channel closed

### ISSUE THREAD

**Issue by aryankanwar** [andywer/threads.js#164]
Getting channel closed error 
**Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:554:16)
    at Worker.send (/app/node_modules/threads/lib/worker.node/worker.js:108:16).**

Getting this error if used worker threads to upload large excel files one after another
This is maybe due to the previous threads are still processing /have not been killed hence when a new pool is made for another request the previous threads are still busy processing.

```
const Threads = require('threads');
const Pool = Threads.Pool; 
const workerPool = new Pool();

module.exports = class JobManager {
    static bufferedJob(pathToScript, params, callback){
        workerPool
        .run(pathToScript)
        .send(params)
        .on('done', (result, input) => {
            console.log(`Worker Job done: ${pathToScript} `);
            callback(null, result);
        })        
        .on('error', (job, error) => {
            console.log(`Error in executing Worker Job: ${pathToScript}`);
            callback(job || error);
        }).on('abort',  (job, error)=>{
            console.log(`Abort Worker Job: ${pathToScript}, Error : ${error}`);
            callback(job || error);
        })
    }
}
```

**Comment by andywer** [comment]
Hey @aryankanwar!

Looks like you are still using threads.js v0.x. I cannot easily tell what the error is in this case and also its whole setup was much more error-prone then the new v1.0 API.

Can you take a look if updating to v1.0 is an option? I know it's a big step as v1.0 comes with an all-new API, but believe me it's worth it 🙂

**Comment by aryankanwar** [comment]
Can you provide with the new API of version 1.0/ Modify my snippet so that
I can rewrite it from v 0.x as I could not see events based calling on the
website.
https://threads.js.org/usage#thread-pool


const Threads = require('threads');
const Pool = Threads.Pool;
const workerPool = new Pool();

module.exports = class JobManager {
    static bufferedJob(pathToScript, params, callback){
        workerPool
        .run(pathToScript)
        .send(params)
        .on('done', (result, input) => {
            console.log(`Worker Job done: ${pathToScript} `);
            callback(null, result);
        })
        .on('error', (job, error) => {
            console.log(`Error in executing Worker Job: ${pathToScript}`);
            callback(job || error);
        }).on('abort',  (job, error)=>{
            console.log(`Abort Worker Job: ${pathToScript}, Error : ${error}`);
            callback(job || error);
        })
    }
}

**Comment by andywer** [comment]
The new API is not event-based, as the event-based approach is pretty error-prone by its very nature.

Your code would now look something like this (haven't tested it yet, though):

```js
const { spawn, Pool, Worker } = require('threads');
const workerPool = new Pool(() => spawn("./path/to/pool-worker"));

module.exports = class JobManager {
    static bufferedJob(pathToScript, params, callback){
        workerPool
          .queue(async worker => {
            let result
            try {
              result = await worker(...params)
            } catch (error) {
              console.log(`Worker job errored:`, error)
              return callback(error)
            }
            console.log(`Worker job done.`)
            callback(null, result)
          })
    }
}
```

Important difference: You are not supposed to pass a worker script path for every pool job creation. In 99% of use cases you will probably never need to spawn different workers in a pool.

If you have multiple different workers and it's not clear which worker a pool job will need to run on, then just create a new worker that combines the functionality of the other workers.

May I point out, too, that your provided sample code comes with a bunch of code smells. Here are some actionables to improve the code quality 🙂

- There is no need to have a class if you only have a static method
  - In a proper OOP manner, the method is not static and the pool is an instance variable, initialized by the constructor
  - I don't see a use case for a class here at all - just export a function ;)
- The callback-based API feels very old-fashioned and leaves room for a multitude of subtle issues, especially around error handling if you are not careful
  - Use promises and async functions

Closing the issue for now. Tell me if that works for you.

**Comment by aryankanwar** [comment]
Thanks for the detailed explanation will update the version and new API
