### ISSUE TITLE
Your sponsor button is not working...

### ISSUE THREAD

**Issue by philkunz** [andywer/threads.js#166]
Just tried to click sponsor, and it threw some error...

**Comment by andywer** [comment]
Yeah, I am still not whitelisted for the GitHub sponsors beta... I can disable it completely for the time being.

**Comment by andywer** [comment]
Haha, success. I just quickly set up a Patreon and a Ko-Fi account as they are also supported!

I still need to add some more content, but they should already be functional 🚀
