### ISSUE TITLE
`done` event never gets called

### ISSUE THREAD

**Issue by andrakis** [andywer/threads.js#17]
I am trying to follow one of the examples, the [Progress Update Example](http://threadsjs.readthedocs.io/en/latest/#progress-update). I get the progress messages, but the master thread never receives the `done` event. This is occurring on all other examples I try too.

Here is the code I'm running:

```javascript
const threads = require('threads');
const config  = threads.config;
const spawn   = threads.spawn;

const thread = spawn(function() { });

thread
 .run(function(input, done, progress) {
    setTimeout(done, 1000);
    setTimeout(function() { progress(25); }, 250);
    setTimeout(function() { progress(50); }, 500);
    setTimeout(function() { progress(75); }, 750);
  })
  .send()
  .on('progress', function(progress) {
    console.log(`Progress: ${progress}%`);
  })
  .on('done', function() {
    console.log(`Done.`);
  });
```

Most of the examples are not full source code examples. I have no idea where `thread` is supposed to come from - perhaps I got it wrong.

Here is the output I get:

```
$ node index.js
Progress: 25%
Progress: 50%
Progress: 75%
```

I have to CTRL+C to get out, as nothing further ever happens.

I would like to know what I'm doing wrong here. Perhaps some working examples could be provided with the package, since at the moment the code fragments on the documentation are incomplete.

**Comment by andywer** [comment]
Hi @andrakis!

Try `on('message', function () {})` instead of `on('done', function () {})` please.
If this is really the issue I am going to fix it, I promise! ;)

**Comment by andrakis** [comment]
Hi @andywer, thank you for the fast response!

This is indeed the issue, one needs to listen for the 'message' event rather than 'done'.

I think a small cleanup of the examples may be in order. I could make a pull request with the changes to Readme.md that I think are appropriate. At the moment you cannot simply copy/paste them to see them in action, which makes picking up the library a little more tricky than it should be.
