### ISSUE TITLE
Shouldn't default pool size be one less than navigator.hardwareConcurrency?

### ISSUE THREAD

**Issue by funwithtriangles** [andywer/threads.js#178]
The default pool size is set using `navigator.hardwareConcurrency`:

https://github.com/andywer/threads.js/blob/218f1c67332b48e242fff2789f50847631ae7352/src/master/implementation.browser.ts

Should it not be one less, becausethe main thread takes one up? Please note that I'm not an expert in this area and am more curious than anything else! Hope that this sort of discussion is suitable here. Thanks!

**Comment by andywer** [comment]
Hey Alex. It's a fair question and providing defaults is not an exact science, not even if you've got some information about the present hardware.

It depends on whether the master thread and the pool workers both tend to run at close to 100% CPU consumption. If not, it's not an issue. If they are all at 100%, then you are right, but the question is still if it actually causes any harm (hard to tell, shouldn’t have much impact).

Different processes are sharing the same CPU cores all the time, anyway, on an operating system level. Using `navigator.hardwareConcurrency` is more about using some sane default, not to find the perfect sweet spot. Also, if we were to subtract one from the core count we would also need to make sure it’s not zero for single core CPUs 🤓

Hope that clarifies things a bit. Feel free to challenge my point of view, but I'm closing the issue for the time being.

**Comment by funwithtriangles** [comment]
Thanks for such a detailed response! Totally makes sense, especially having to check for single core CPUs. :)
