### ISSUE TITLE
Can't resolve child_process from tiny worker (tiny-

### ISSUE THREAD

**Issue by mcongy** [andywer/threads.js#183]
Hello, great job with the lib!

Unfortunately, I can't get it to work.

I'm using webpack + babel preset typescript to transpile my code.
I followed all the steps in the documentation.

Relevant parts of my webpack config:
```javascript
module.exports = {
  node: false,
  target: 'node',
  externals: { 'tiny-worker': 'tiny-worker' },
  module: {
    rules: [
      {
        test: /\.(js|ts)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env',
                {
                  targets: { node: '12.16.3' },
                  useBuiltIns: 'usage',
                  modules: false,
                  corejs: 3,
                  loose: true
                },
                '@babel/preset-typescript'
              ]
            ],
            plugins: [
              '@babel/plugin-proposal-optional-catch-binding',
              ['@babel/plugin-proposal-decorators', { legacy: true }],
              ['@babel/plugin-proposal-class-properties', { loose: true }]
            ]
          }
        }
      }
    ]
  }
}
```

Error I'm getting:
```
[WEBPACK] [
  ModuleBuildError: Module build failed (from ./node_modules/threads-plugin/dist/loader.js):
  ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in 'C:\Projects\core\node_modules\tiny-worker\lib'
      at C:\Projects\core\node_modules\webpack\lib\Compilation.js:925:10
      at C:\Projects\core\node_modules\webpack\lib\NormalModuleFactory.js:401:22
      at C:\Projects\core\node_modules\webpack\lib\NormalModuleFactory.js:130:21
      at C:\Projects\core\node_modules\webpack\lib\NormalModuleFactory.js:224:22
      at C:\Projects\core\node_modules\neo-async\async.js:2830:7
      at C:\Projects\core\node_modules\neo-async\async.js:6877:13
      at C:\Projects\core\node_modules\webpack\lib\NormalModuleFactory.js:214:25
      at C:\Projects\core\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:213:14
      at C:\Projects\core\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5
      at eval (eval at create (C:\Projects\core\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
      at C:\Projects\core\node_modules\webpack\lib\NormalModule.js:316:20
      at C:\Projects\core\node_modules\loader-runner\lib\LoaderRunner.js:367:11
      at C:\Projects\core\node_modules\loader-runner\lib\LoaderRunner.js:182:20
      at context.callback (C:\Projects\core\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
      at C:\Projects\core\node_modules\threads-plugin\dist\loader.js:3999:23
      at C:\Projects\core\node_modules\webpack\lib\Compiler.js:343:11
      at C:\Projects\core\node_modules\webpack\lib\Compiler.js:681:15
      at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\core\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
      at AsyncSeriesHook.lazyCompileHook (C:\Projects\core\node_modules\tapable\lib\Hook.js:154:20)
      at C:\Projects\core\node_modules\webpack\lib\Compiler.js:678:31
]
```

The code I'm trying to execute is the "caluclatePi" example.

I've tried many different approaches and combinations of the configuration. I even tried using nodeExternals from the webpack-node-externals package.

Is there something I'm doing wrong?

Thank you for your time!

**Comment by andywer** [comment]
Hey @mcongy!

Can you try adding

```
  "browser": {
    "tiny-worker": false
  }
```

to your `package.json`?

**Comment by andywer** [comment]
PS: Try to drop the `externals` from your webpack config, too.

**Comment by mcongy** [comment]
@andywer Thanks for qucik response.

Tried
```javascript
  "browser": {
    "tiny-worker": false
  }
```
and removing externals from webpack config (and all the combinations with everything else).

Unfortunately, the problem still persists.

**Comment by andywer** [comment]
Can you try

```
  "browser": {
    "child_process": false
  }
```

instead?

**Comment by andywer** [comment]
Btw, do you by any chance use `tiny-worker` in your code?

**Comment by mcongy** [comment]
Tried adding child_process to the browser property in package.json, without any luck 😢 

I'm not using tiny-worker anywhere in my code.

Here's my tsconfig.json:
```javascript
{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "node",
    "module": "commonjs",
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["esnext"],
    "outDir": "__dist",
    "declarationDir": "__dist/types",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "paths": {
      ...
    }
  },
  "include": ["src/**/*", "types/**/*", "cli/**/*"]
}
```

**Comment by mcongy** [comment]
tiny-worker isn't used even in any of my transitive dependencies.

Tried having tiny-worker both installed and not installed.

**Comment by andywer** [comment]
Man, this is weird... One more try, this time try to add this to your webpack config (top-level, not in the babel loader config):

```
plugins: [
  new webpack.IgnorePlugin({
    requestRegExp: /tiny-worker/
  })
]
```

**Comment by mcongy** [comment]
I tried setting target to 'web', and it compile successfully.

I tried adding webpack Ignore plugin, and it seems like it works: now it complains about not being able to resolve 'os' package.

I think the problem is that webpack's external property only ignores direct dependencies (dependencies imported in my own code), not transitive dependencies.

I'll try to solve this by ignoring all node's native modules using IgnorePlugin. Will let you know.

Thank you for your assistance!

**Comment by andywer** [comment]
Good to hear! It's still weird, though, since threads.js [tells webpack explicitly](https://github.com/andywer/threads.js/blob/master/package.json#L90) what to ignore when building a  browser bundle and that works fine.

So you still have to add the `IgnorePlugin` when the target is explicitly `web`?

**Comment by mcongy** [comment]
> So you still have to add the `IgnorePlugin` when the target is explicitly `web`?

No. Using `IgnorePlugin` with target `node` works well.

**Comment by EvgenyRodygin** [comment]
Hey guys,
I have exactly same symptoms as mcgony had, with the only difference that the library eventually can't find the modules at runtime after adding all node modules to the IgnorePlugin.
For me it is currently the "os" module:
`Error: Cannot find module 'os'
    at webpackMissingModule (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/implementation.node.js?:9:45)
    at eval (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/implementation.node.js?:9:122)
    at Module../node_modules/threads/dist-esm/master/implementation.node.js
    at __webpack_require__ 
    at eval (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/implementation.js?:6:78)
    at Module../node_modules/threads/dist-esm/master/implementation.js
    at __webpack_require__
    at eval (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/index.js?:4:73)`

I use target: "node". Is there any info I can provide to resolve this?
