### ISSUE TITLE
Example of pool plus observable?

### ISSUE THREAD

**Issue by pamelafox** [andywer/threads.js#195]
Thanks for the lovely library, I'm using it to develop a demonstration of parallel programming with machine learning for high school students. 

I am currently working on visualizing the worker progress in a Gantt chart using the taskStart/taskCompleted events. However, I would like to visualize more fine-grained progress than that, so I would like each worker to notify the page with its current progress ("Loaded model", "Classified image", etc). 

It looks like the way to do that is by returning an observable. I'm not sure how to subscribe to the observable when I'm queueing events in a pool, however.

My current attempt looks like this:
    pool.queue(async handleImage => {
        return handleImage(dataObj).subscribe(updates => {
            console.log("Updates", updates);
        });
    });

But that doesn't seem to be correct. Do you know the correct syntax for subscribing to observables when using the pool?

(If that code does look correct, then I'll inspect my worker code instead).

Thank you!

**Comment by andywer** [comment]
Hey @pamelafox! Thanks 🙂

Ahh, I think the issue here is that `pool.queue()` awaits whatever the callback returns – so if you return the observable subscription, the `await` will be useless. We should make `pool.queue()` treat observable subscriptions.

I would hope that this work-around does the trick for now:
```js
  const imageProcessing = handleImage(dataObj)
  const subscription = imageProcessing.subscribe(/* ... */)
  imageProcessing.finally(() => subscription.unsubscribe())
  return imageProcessing  // <- this works because under the hood each worker call returns an "observable promise" which implements both interfaces
```

PS: That's pretty cool. I wish we had done anything like this in high school! 😉

**Comment by pamelafox** [comment]
Thanks for the code! I tried it out and there was no JS error, but I didn't see any updates. I then also tried the much simpler example from the docs, and not even using a pool, but still didn't see updates. So I think there's some issue with my setup (perhaps my bundler/transformer?) that's preventing observables from working properly. It's okay, the demo works fine without the fine-grained progress.

Parallel programming is part of the new CollegeBoard AP CSP exam, so ~100K students will be learning parallel programming next year. This demo is intended to help them grasp the concept, and I'll be linking to it from my Khan Academy CSP content. I'll ping the URL to you when it's up on Github.

You can close this ticket, unless you think there's further work to be done.

**Comment by pamelafox** [comment]
@andywer I've uploaded the current demo to https://pamelafox.github.io/parallel-demo/ ..I still need to get Transferable working on it, but you get the idea.

**Comment by YassienW** [comment]
@pamelafox Did you manage to get this working? I seem to have the same issue where the updates fall through.

**Comment by pamelafox** [comment]
I never got observables working, no.

**Comment by andywer** [comment]
Ahh, that's a shame, @pamelafox!

Was it due to the pool + observables, did my workaround idea not work?

**Comment by YassienW** [comment]
I managed to get observables working with a pool, but subjects don't seem to work.
I had to save the observer in a variable and call it from around my worker.

@andywer any hints as to why that is? I'm using the same exact pattern i used with observables but returning `Observable.from(subject)`
