### ISSUE TITLE
Gulp support?

### ISSUE THREAD

**Issue by m0ngr31** [andywer/threads.js#205]
Any chance at all this could be made to work with Gulp?

**Comment by andywer** [comment]
Hey! How do you mean? Gulp is just a task runner 😉

**Comment by m0ngr31** [comment]
Sorry, the app in question is being built with Gulp. Trying to figure out a way to get this working on it.

**Comment by andywer** [comment]
Yeah, that completely depends upon the tools you run with gulp.

Closing for now as it's not actionable so far. Feel free to re-open if you think there is a concrete issue.
