### ISSUE TITLE
Support allSettled like functionality with pool.completed

### ISSUE THREAD

**Issue by kellyselden** [andywer/threads.js#208]
It seems to me that `pool.completed()` resolves on the first errored task ([here](https://github.com/andywer/threads.js/blob/12a43f37f0/src/master/pool.ts#L258)). Is it possible to treat it like `Promise.allSettled` and let all the tasks finish regardless of error?

**Comment by andywer** [comment]
Hey Kelly!
Yeah, that makes sense 👍

**Comment by andywer** [comment]
Check out #209. What do you think? 😉
