### ISSUE TITLE
Pool of workers to execute a function with changing argument

### ISSUE THREAD

**Issue by lateiskate** [andywer/threads.js#213]
I have a very large data that I need to treat off-mainThread. But then again, spawning one worker to treat this large data is kind of inefficient.
I noticed the **Thread Pools** but that seems to just offload work to several threads. But my case requires the same function **but with a changing argument**

I tried:
```js
let chunks = [ [DataChunk], [DataChunk] ]
		let q = [];
		for (let chunk of chunks) {
			q.push(async () => {
				let chWorker = await spawn(new Worker("./function"))
				let s = await chWorker.TREAT(chunk)
				await Thread.terminate(chWorker)
				return s
			})
		}
		const responses = await Promise.all(q);
```
If there's only **one** Data Chunk, it works flawlessly, but once its two or more. I face 

> Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

I'd really like a solution. thank you!

**Comment by andywer** [comment]
Hey @lateiskate, I am a bit puzzled.
You are not even using a pool in your example… 😉

Try a thread pool instead:

```js
const pool = Pool(() => spawn(new Worker("./function")))
const chunks = [ /* ... */ ]
const responses = []

for (const chunk of chunks) {
  pool.queue(async worker => {
    const s = await worker.TREAT(chunk)
    responses.push(s)
  })
}

await pool.completed()
await pool.terminate()
```

(I just wrote that code down, I didn't try to run it – but it should convey the idea)

**Comment by lateiskate** [comment]
@andywer I'm aware that I'm not using a pool in the example. I just thought that the pool required the same type of static function to be treated by a set of different pool threads. So I just to explain the concept of what I need/want to do
Regardless, I tried the Thread Pool but the timeout issue happened once there were like 12 data chunks.

> Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
> at Timeout.setTimeout [as _onTimeout] (/home/test-zone/node_modules/threads/dist/master/spawn.js:34:53)
> at ontimeout (timers.js:436:11)
> at tryOnTimeout (timers.js:300:5)
> at listOnTimeout (timers.js:263:5)
> at Timer.processTimers (timers.js:223:10)

I await for like 5000ms before proceeding to queueing and await for like 100ms before adding each chunk to the queue but i still face the timeout

**Comment by andywer** [comment]
@lateiskate If your main issue is that you are running into the timeout, try increasing it, like so:

```js
spawn(new Worker("./worker"), { timeout: 30000 })
```

I don't know what device of what platform you are running the code on, but these timeout errors often hint towards problems with your worker. Maybe you didn't call expose() or the worker crashed before it could expose() anything?

**Comment by lateiskate** [comment]
@andywer Yep, increasing the timeout solved it for me!
Thanks a lot! _(and thanks for the awesome package)_
