### ISSUE TITLE
Is `pool.completed()` queue related?

### ISSUE THREAD

**Issue by lateiskate** [andywer/threads.js#218]
Hello, i hope you are having a nice day.
So I was wondering, Let's say I have a pool made with the workers using a file with **several** functions exposed, if client is queueing different tasks using the pool, how do I know that they finished independently?

As in, the worker file has 3 different functions exposed (**A**, **B** and **C**). **A** is really taxing and can take long to process. **B** and **C** however are kind of easier to execute.
If client queues A and then queues B and C right after, am I going to get the response once A is executed when using pool.completed()? Or will I get the response after **all functions are executed**?
In the same concept, if function A is queued 3 times in a row, will I get the response of the first queue right when it's done? or untill all the 3 are done?

**Comment by andywer** [comment]
Hey @lateiskate!

The `pool.completed()` promise will resolve once the queue is drained and there all running tasks are finished.

Hope that answers your question 🙂

I think the JSDoc describes it like that, too, but the website might not. Should we update the website or where did you look for that information?

**Comment by andywer** [comment]
PS: A PR with a proposal for a better documentation is of course always appreciated 😉

**Comment by lateiskate** [comment]
@andywer Ah thanks for explanation. I guess the only way to treat it is to have multiple pools? each pool only doing one exposed *different* function. (but then again, i hope it's not very taxing)

I read [threads.js.org/usage-pool](https://threads.js.org/usage-pool) and tried to find a reference to my question :D 
As for PRs, I really don't use GitHubs that much haha. This package was the first one I have actually made an "issue" in. Thanks for the awesome package again:)

**Comment by andywer** [comment]
Ahh, I think I didn't completely understand your question yet… Do you mean how to tell if all invocations of only A finished, for instance?

Since each call to `pool.queue()` returns a promise that resolves once the pool job is done you can first queue all the jobs that need to be done while keeping track of their promises using an array. You can then `await Promise.all(allMyPoolJobPromisesA)`.
