### ISSUE TITLE
Pool stops processing

### ISSUE THREAD

**Issue by FlorianBruckner** [andywer/threads.js#22]
I got a use case where I am submitting a large number of similar jobs to a pool.

Problem is, on my machine with 8 cores processing stops after 10 jobs. The reason for this seems to be the way events are handled. 

When I submit my 20000 jobs, there are 19992 listeners registered for the threadAvailable event. 
When a first job is done and a thread is available, the event emitter removes all listeners (due to https://github.com/primus/eventemitter3/issues/63) and then calls dequeue for all listeners 19992 events. When the event processing is finished, we end up with a single listener for the threadAvailable event. This is because in the event emitter, the event array is cleaned for every iteration of the loop.

When the next job finishes, we have a single listener for the threadAvailable event. Event emitter clears the event listeners for the event and calls dequeue once. Because at this time, a thread is available and the job queue is not empty, there is no listener registered.

Thus, job processing stops at this point.

I am able to work around this issue by calling dequeue when a job is done. But I believe this is just a workaround.

**Comment by FlorianBruckner** [comment]
Was browsing through the issues again, and I think this might be the root cause for #21 as well.

**Comment by andywer** [comment]
Cool, thanks for debugging!!

Sorry that I had so little time to look into this (#21). Your explanation seems very profound, I will definitely check this out. The event handling behavior is really not that good.

Will let you know when I fix the code.

> I am able to work around this issue by calling dequeue when a job is done.
PS: What do you mean by "calling dequeue"?

Cheers!

**Comment by FlorianBruckner** [comment]
When the job is done, I call dequeue() on the pool in my callback where I process the result.

**Comment by andywer** [comment]
Please try https://github.com/andywer/threads.js/tree/flobru-fixes! #22 (and therefor #21) and #23  should be fixed now. Also added a unit test for this case which is green now after the fix. And there will be only one `threadAvailable` listener on the pool, not one per job :)

**Comment by FlorianBruckner** [comment]
Works as expected. Thanks again!

**Comment by andywer** [comment]
Fixes are published as version 0.7.0 🎉🎉

**Comment by dcerisano** [comment]
Not fixed on Windows 10.
