### ISSUE TITLE
Expose `isWorkerRuntime` as part of public API

### ISSUE THREAD

**Issue by jtfell** [andywer/threads.js#225]
I would like to be able to conditionally call the `expose` function based on whether I'm loading a module in a worker or not. Eg.

```ts
import { expose, isWorkerRuntime } from 'threads';

export function helper(): number {
  return 4;
}

if (isWorkerRuntime()) {
  expose(helper);
}
```

This way I can use this utility library as a worker or directly in the main thread depending on the use case.

**Comment by kellyselden** [comment]
Could this be accomplished with

```
if (require.main === module) {
  expose(task);
} else {
  module.exports = task;
}
```

This is how I'm doing it. If so, maybe it makes sense to deprecate `isWorkerRuntime`?

**Comment by kellyselden** [comment]
Ah I guess in browsers to need an abstraction... Nevermind me.

**Comment by andywer** [comment]
Yeah, there is more to it, but your conclusion is still true, @kellyselden. There is no substitute for `isWorkerRuntime` and since we need it under the hood, anyway, there is no reason not to export it 🙂
