### ISSUE TITLE
superfluous / in script URL

### ISSUE THREAD

**Issue by FlorianBruckner** [andywer/threads.js#23]
Another one I was caught in:

I have a script I intend to use for a pool. Using webpack, I generated the path to this file and this results in the following:

        /path/worker.js

Further, I configure the base path like this:

        basepath: {
          web: "http://localhost:8084",
          node: ""
        }

When constructing the Pool, Chrome complains about not being able to load the script, because this URL is generated:

      http://localhost:8085//path/worker.js

Note the additional / in the path. My workaround for this is to remove the leading slash from the otherwise perfectly valid path. But I believe the additional / is just wrong, because when combining script path and basepath, the script path needs to be absolute anyway, thus the leading slash would need to be always there.

**Comment by andywer** [comment]
Thanks, @FlorianBruckner! Good point. Will have a look what causes that odd path joining behavior 👍

**Comment by FlorianBruckner** [comment]
Thanks, works for me.
