### ISSUE TITLE
Setting spawn timeout (current default is 10,000 ms)

### ISSUE THREAD

**Issue by juicetin** [andywer/threads.js#231]
Hi,

At the moment, the only way to set the spawn timeout is by using the environment variable `THREADS_WORKER_INIT_TIMEOUT` Would it be possible to add an extra option to the third arg  in `spawn` that would allow setting this in code?

Thanks!

**Comment by andywer** [comment]
Sure! Would you mind preparing a PR?

**Comment by andywer** [comment]
Closed by #206.
