### ISSUE TITLE
DataCloneError: Failed to execute 'postMessage' on 'Window': ErrorEvent object could not be cloned.

### ISSUE THREAD

**Issue by Christilut** [andywer/threads.js#233]
I'm getting this error reported in Sentry:
```
Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
```

With another error:
```
Not reporting uncaught error back to master thread as it occured while reporting an uncaught error already. Latest error: DataCloneError: Failed to execute 'postMessage' on 'Window': ErrorEvent object could not be cloned.
```

The second error might be unrelated, it's hard to see in Sentry. But it seems to happen 9 or 10 seconds before the timeout error so that matches up.

Seems to happen to both Chrome 80 and Safari 13 users.

Any idea what might be causing this? My workers all call expose():

```js
import { expose } from 'threads/worker'

...

 expose({
    getCommonLocations
  })
```

**Comment by andywer** [comment]
Hey @Christilut!

Something goes wrong in the worker while trying to communicate with the master thread for the first time, but then the postMessage() fails because it cannot clone the error.

There are two open questions: Chances are that there is an error in the worker on initialization, before expose() is done. What’s that error and why can this error not be postMessage()-ed?

Can you reproduce the error locally? A console.log() or two would be the easiest way to go here.

Otherwise we can only try to come up with better error reporting for those edge cases.

**Comment by Christilut** [comment]
Well I use threads in 5 places and Sentry is being super unhelpful in showing me where the error occurs. But every file that I use threads is similar:

```ts
import { expose } from 'threads/worker'

function getCommonLocation() {
...
}

if (process.env.NODE_ENV !== 'test') {
  expose({
    getCommonLocations
  })
}
```

Other than some more imports at the top, there is nothing at all going on in these files that could be going wrong. The imports are just classes without side effects so nothing that can error there.

I think I can reproduce it but it's a very odd bug and when reproducing it it doesn't seem to have any negative effects. Looks like it happens when something is loading (ag-grid) and I press the back button before it's done loading. So maybe I should just ignore this error.
When reproducing it's not showing the me 10000ms timeout error though, only the inner postMessage warning.

And the weird part is, is that the stacktrace shows the error in a file that's not referred to when the error happens:
```
  | postUncaughtErrorMessage | @ | index.js:88
-- | -- | -- | --
  | (anonymous) | @ | index.js:156
  | setTimeout (async) |   |  
  | (anonymous) | @ | index.js:156
  | error (async) |   |  
  | (anonymous) | @ | index.js:154
  | ./node_modules/threads/dist-esm/worker/index.js | @ | index.js:177
  | __webpack_require__ | @ | bootstrap:790
  | fn | @ | bootstrap:150
  | ./node_modules/threads/dist-esm/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:790
  | fn | @ | bootstrap:150
  | (anonymous) | @ | Private.js:6970
  | ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Private/Features/HealthCheck/TracksWithoutPlaylist.vue?vue&type=script&lang=ts& | @ | Private.js:7074
  | __webpack_require__ | @ | bootstrap:790
  | fn | @ | bootstrap:150
  | ./src/views/Private/Features/HealthCheck/TracksWithoutPlaylist.vue?vue&type=script&lang=ts& | @ | TracksWithoutPlaylist.vue?14db:1
  | __webpack_require__ | @ | bootstrap:790
  | fn | @ | bootstrap:150
  | ./src/views/Private/Features/HealthCheck/TracksWithoutPlaylist.vue | @ | TracksWithoutPlaylist.vue:1
  | __webpack_require__
```

Is there any way to add more logging somewhere? Looks like it's swallowing an error that it can't do a postMessage for?

**Comment by andywer** [comment]
I think that the issue is that this code https://github.com/andywer/threads.js/blob/07c4d3abd13f876a3845b21b25b1f61a3ee872f2/src/worker/index.ts#L93-L108 only reports the secondary error, but not the original error.

Let's report both!

**Comment by andywer** [comment]
@Christilut Try `npm install threads@1.4.0-error-reporting-fix` – this is the fix #235 published under a `testing` tag.

**Comment by Christilut** [comment]
Thanks! I have real trouble reproducing the problem so I've just sent this branch out in the wild and see what it reports back. Might be a few days or so until this occurs again, kind of sporadic.

**Comment by Christilut** [comment]
Missing a `util.inspect` I think :)
```
Not reporting uncaught error back to master thread as it occured while reporting an uncaught error already. Latest error: DataCloneError: Failed to execute 'postMessage' on 'Window': ErrorEvent object could not be cloned.  Original error: [object ErrorEvent]
```

**Comment by andywer** [comment]
@Christilut Ohh, didn't notice your issue… What platform / browser are you using? There should be no `util.inspect()` necessary (which would also increase the bundle size a little bit – trying to avoid if possible).

I just tried a simple (maybe oversimplified?)

```js
console.log('x:', { foo: 1 }, 'y:', { bar: 2 }, 'z:', { baz: 3 })
```

in node.js 10 and Chrome and in both I got the expected output:

```
x: { foo: 1 } y: { bar: 2 } z: { baz: 3 }
```

**Comment by Christilut** [comment]
I'm seeing the same 
```
Not reporting uncaught error back to master thread as it occured while reporting an uncaught error already. Latest error: DataCloneError: Failed to execute 'postMessage' on 'Window': ErrorEvent object could not be cloned.  Original error: [object ErrorEvent]
```

on Chrome 80 and Safari 13

**Comment by Christilut** [comment]
But this is reported with Sentry though

**Comment by andywer** [comment]
Ohh, right – so then it's probably a Sentry issue. I thought it was fine after getting positive confirmation from another user: https://github.com/andywer/threads.js/issues/234#issuecomment-618762166

To be fair, this is quite edge-casy what we are doing here – I wouldn't blame Sentry for having issues with that setup… 😅

**Comment by Christilut** [comment]
Can we get more useful error info out of this through Sentry though? I wish I could reproduce the problem but still haven't been able to anymore

**Comment by andywer** [comment]
We could try to monkey-patch the code to see if this works:

```js
console.error(/*...*/"Original error:", { ...originalError, message: originalError.message, error: originalError.error && { ...originalError.error, message: originalError.error.message } })
```

**Comment by Christilut** [comment]
Does Sentry report console.error? Or do you mean including this in the error message?

**Comment by andywer** [comment]
I meant replacing `originalError` in the existing `console.error()` call with the big `{ ...originalError, /*...*/ }` object expression.

And sure, Sentry reports that. I mean you have been seeing these error messages for the past days, right? 😉

**Comment by Christilut** [comment]
Awesome! Yes I've been seeing lots of these actually, should be soon that we'll find the real cause.

**Comment by Christilut** [comment]
@andywer Can you make a patch so I can put it online?

**Comment by andywer** [comment]
Well, I cannot release that quirk to production, but I could publish a version using a testing tag.

I thought you already deployed a monkey-patched version…

**Comment by Christilut** [comment]
Sorry, I thought you'd update the earlier branch I was testing on

**Comment by andywer** [comment]
Ohh, I see. For reference, this is the previously published fix: https://github.com/andywer/threads.js/issues/233#issuecomment-615932478

Yeah, sorry, but there are just so many things to care about right now that I didn't realize that we already had this testing release earlier in the proceedings of this issue.

Let me publish a new testing version…

**Comment by andywer** [comment]
Alright! Published it as `threads@1.4.1-extended-error-reporting`.

Find the code on this branch: [`bugfix/233-worker-error-reporting`](https://github.com/andywer/threads.js/tree/bugfix/233-worker-error-reporting)

**Comment by Christilut** [comment]
Thanks! I'll report back in a few days with news

**Comment by Christilut** [comment]
```
vue-router.esm.js:2113 Error: expose() called in the master thread.
    at expose (index.js:127)
    at Module../src/helpers/features/genre-renamer.ts (genre-renamer.ts:17)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Private/Features/SimilarTracks/index.vue?vue&type=script&lang=ts& (Private.js:9031)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module../src/views/Private/Features/SimilarTracks/index.vue?vue&type=script&lang=ts& (index.vue?66ed:1)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
```

I think this was the error. I was importing a function from the genre-renamer.ts file which also called expose().

In another file I used the expose/spawn method to run the function but in this file I imported it directly. I guess as a side effect it also ran expose() in the master thread.

**Comment by andywer** [comment]
Ahhh. How did you get to see this error now? I guess it's unrelated to our latest error reporting advance.

**Comment by Christilut** [comment]
In one file I have this:
```
import { findAllUniqueGenres } from '../../../../helpers/features/genre-renamer'
```

genre-renamer.ts:
```
import { expose } from 'threads/worker'
import { Track } from '../../classes/track'

export function findAllUniqueGenres(tracks: Track[]): string[] {
 ...
}

if (process.env.NODE_ENV !== 'test') {
  expose({
    findAllUniqueGenres
  })
}
```

**Comment by Christilut** [comment]
Still haven't figured this one out... My sentry now looks like this:
![image](https://user-images.githubusercontent.com/3471363/83109945-914c0780-a0c2-11ea-8322-3a0811221a4f.png)

And there doesn't appear to be an underlying error anymore:
![image](https://user-images.githubusercontent.com/3471363/83109989-a4f76e00-a0c2-11ea-9eec-1b0ce1ec0b4f.png)


I can't reproduce it and I can't tell if this is actually bothering users or not... No one has complained yet but they rarely do.

Any ideas to track this down?
