### ISSUE TITLE
Webpack production mode generating conflict

### ISSUE THREAD

**Issue by Pipas** [andywer/threads.js#238]
When the flag for the Webpack mode is set as production the workers are both compiled to `0.bundle.worker.js` leading to this warning:

```WARNING in Conflict: Multiple assets emit different content to the same filename 0.bundle.worker.js```

If the flag is set to development it works correctly.

Here is my **webpack.common.js**
```
const path = require('path')
const ThreadsPlugin = require('threads-plugin')

module.exports = {
  entry: './src/index.ts',
  plugins: [new ThreadsPlugin()],
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
        options: {
          compilerOptions: {
            module: 'esnext',
          },
        },
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'public'),
  },
}
```

and here is the **dev** and **prod** configs respectively:
```
const merge = require('webpack-merge')
const common = require('./webpack.common.js')

module.exports = merge(common, {
  mode: 'development',
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './public',
  },
})
```

```
const merge = require('webpack-merge')
const common = require('./webpack.common.js')

module.exports = merge(common, {
  mode: 'production',
})
```

I'm using Webpack 4.42.0

**Comment by andywer** [comment]
Hey @Pipas!

I wish I could tell you something smart straight away, but I don't see anything obviously wrong about it and webpack configurations are a bi***.

Maybe @kalbert312 has an idea. He had a similar error at one point in andywer/threads-plugin#13 that disappeared.

PS: Are you on the latest `threads-plugin` version?

**Comment by Pipas** [comment]
Yes, I did a fresh npm install and I'm running the latest version, here is an excerpt from my package.json file with the relevant packages:

```
    "threads-plugin": "^1.3.1",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3",
    "webpack-merge": "^4.2.2"
  },
  "dependencies": {
    "threads": "^1.4.0",
```

**Comment by andywer** [comment]
Sorry for the late response! I hope you haven’t given up yet.

New thought: Did you configure the ASAR unpacking as documented here: https://threads.js.org/getting-started#electron?

**Comment by Pipas** [comment]
It appears to have fixed itself. I stopped working on the project for about 2 weeks and now that I tried it again it just works as expected.

**Comment by andywer** [comment]
Webpack 🤷‍♂️  😅

Thanks for the update, though! Let's close it for now.
