### ISSUE TITLE
Job repeatedly requests Script from server

### ISSUE THREAD

**Issue by FlorianBruckner** [andywer/threads.js#24]
This is rather an enhancement idea than a defect.

When a job executes in the pool, it reloads the worker with the script to execute. When this script is loaded using a URL, Chrome requests the script with Cache-Control: no-cache from the server.

In my use case with 20000 executions of the same job script, I therefore see 20000 requests to the server, each costing about 10ms according to Chrome developer tools.

I believe it should not be necessary to re-read the script or even re-initialize the worker behind the job as long as the job is using the same script as the worker is already initialized with.

**Comment by andywer** [comment]
Nice to see that there is a threads.js user out there who debugs stuff if it does not work! ^^
Sorry, for the inconcenience, though...

But you are right. I am not sure why Chrome sets the `Cache-Control: no-cache`.

One question: I assume you pass exactly the same function (reference) to `.run()`? This should be an easy fix then :)

**Comment by andywer** [comment]
PS: Thank you for your contributions!

**Comment by andywer** [comment]
PPS: Are you using `.run(<function>)`, `.run(<script url>)` or `.run(<function or script>, <importScripts>)`?

**Comment by FlorianBruckner** [comment]
I use once

     new Pool.run("<path to script>.js")

and for each element to process

     pool.send( { params....}).promise().then()

**Comment by FlorianBruckner** [comment]
Thanks for your great support. This one is fixed on the branch flobru-fixes. It now loads the script exactly once per thread. 

Surprisingly, the performance improvement together with the other fixes is quite noticeable. I would not have expected that much overhead from those issues.

**Comment by andywer** [comment]
Awesome that it's such a performance improvement! 🚂💨
