### ISSUE TITLE
where is multipierWorker defined / created ?

### ISSUE THREAD

**Issue by MichaelLiss** [andywer/threads.js#240]
Hi,

I don't see in your example documentation where multiplier is created ? (in the pool.queue call)

pulled code from here https://threads.js.org/usage-pool#pool-basics

```javascript
import { spawn, Pool, Worker } from "threads"

const pool = Pool(() => spawn(new Worker("./workers/multiplier")), 8 /* optional size */)

pool.queue(async multiplier => {
  const multiplied = await multiplier(2, 3)
  console.log(`2 * 3 = ${multiplied}`)
})

await pool.completed()
await pool.terminate()
```

**Comment by MichaelLiss** [comment]
Also,

Would you please provide an example of how I could add a worker to the pool upon some DB trigger.
I don't need the DB trigger code... I have that... but more along the lines of something like this:

Here is my DB notification 
```javascript
    GarminNotification
    .watch()
    .on('change', data => {
        if(data.operationType !== 'insert'){
            return -1
        }
        startWorker_ThreadsGarmin(data.fullDocument);
        return 0
    });
```

This is what I have for the function now:
```javascript
startWorker_ThreadsGarmin = async (fullDocument) => {

    const worker = await spawn(new Worker("./workers/garminWorkerThreads"))
    const result = await worker.processNotification(fullDocument);
  
    console.log("result", result);
  
    await Thread.terminate(worker);
}
```


This is what I would like to do:
```javascript
setupPool = async () => {
    
    var debugThis = false || garminFunctions_all_debugThis;
    if(garminFunctionNames_all_debugThis || debugThis){
        console.log('setupPool' );
    }

    console.log('setting up the worker pool');

    var wi = await getWorkerAndJobsPerWorker();
    pool = Pool(() => spawn(new Worker('./workers/garminWorkerThreads')), wi.workers /* optional size */);
    console.log('pool',JSON.stringify(pool));
}
```


of course get the DB trigger
```javascript
startWorker_ThreadsGarmin(data.fullDocument);
```


Then that function would look something like this:
```javascript
startWorker_ThreadsGarmin = async (fullDocument) => {

    const worker = await spawn(new Worker("./workers/garminWorkerThreads"))
    const result = await worker.processNotification(fullDocument);

// what I don't know is how to create this 'processNofication' object
// and
// how to get notification that the thread is done
// and
// if this is right?  (it's from your example )
  pool.queue(async processNotification=> {
    const multiplied = await processNotification(fullDocument)
    console.log(`2 * 3 = ${multiplied}`)
  })
  
}
```

**Comment by andywer** [comment]
The concept of the pool is that you tell the pool upon creation how to spawn a worker of your choice, the pool then instantiates workers as needed.

> I don't see in your example documentation where multiplier is created ? (in the pool.queue call)

The pool creates the workers using the function you passed to it on its creation. Then you queue a task which is just a callback function. The pool will execute the function is soon as possible, passing an available worker as the first argument to that queued callback function.

So it's supposed to be something like

```js
pool = Pool(() => spawn(new Worker('./workers/worker')), 2 /* optional size */);

MyNotification
    .watch()
    .on('change', data => {
        if(data.operationType !== 'insert'){
            return -1
        }
        pool.queue(worker => worker.processNotification(data.fullDocument));
        return 0
    });
```

**Comment by andywer** [comment]
Can you make a suggestion on how to improve the docs to make it more obvious how to use the pool?

**Comment by MichaelLiss** [comment]
I am still learning web-programming and probably not the person to ask on how to improve documentation for a complex object such as this, as I don't know all the ins-and-outs of where stuff goes and why it goes there, but what you posted helped me a lot !

Generally speaking, my two biggest questions, for any component, is HOW to integrate them into my project and WHERE to call them - in which case, a working sample project speaks volumes.

Thank you

**Comment by andywer** [comment]
Let's create a separate issue for the lack of ready-to-try sample code then 👍
