### ISSUE TITLE
Queue multiple tasks at once in a worker pool

### ISSUE THREAD

**Issue by rigwild** [andywer/threads.js#245]
Hi!

It would be nice to be able to queue multiple tasks in a worker pool in one call.

This could be defined as a rest parameter using [method overloading](https://www.typescriptlang.org/docs/handbook/functions.html#overloads):

```ts
// Queue one task
function queue<Return>(task: TaskRunFunction<ThreadType, Return>): QueuedTask<ThreadType, Return>
// Queue multiple tasks
function queue<Return>(...tasks: TaskRunFunction<ThreadType, Return>[]): QueuedTask<ThreadType, Return>[]

// Result
const res1 = queue(() => {})           // => QueuedTask<ThreadType, number>
const res2 = queue(() => {}, () => {}) // => QueuedTask<ThreadType, number>[]
```

See: [Playground Link](https://www.typescriptlang.org/play?#code/PTAEBEFcFtoT1AFzgBwKYGcCwAoZ7QAVAQwwGsAlSAOwDEaBjRASwHtqAeQgCwCc1iAE0Ko0AGlAU0iSL2oA+UAF5QAb1DEAXET4DhoiQCNtUmXIC+ufGlABFSGgfDSZLrqEj0E07IXK1lniiOvwewSqqgbggdg4OoOw2iC64AGaMLOygAI5xaBw+cvIAFMnk2iTkVHQZbJw8ofpektK+8gCU2vaOaM7kbo2e4i1mCtFg3fHQkAA2LCgzSS7YOOnUTHU5eQWtRcUAdIdlZBgVLtX065n17k3DhQoA2gC6nbE9fa4NekPeu0-PXDjCAweCgZjQBZoaBoajJa5pWpZXI9UAHI7LbTEahwF7tUBqXAE-ijUAAcjJGgwGhxuCiOBiUgws0QuAY7AwiFA-AwAEZ-CiHMV1FpycQyUZtLyAEygcz4gmKpXK5UxJSKSa9SpfW6-UDUGCGNC8eRsjlcnmylSCtDCjTaCmS0AyuUSEUOwwS0DGZ3SgAscvxao1eU+Ax+Bn1huN8heuCAA)

It could then be used like this:
```ts
// worker.ts
const hugeFn = (): Promise<number> => Promise.resolve(Math.random())
const workerMethods = { hugeFn }
export type WorkerMethods = typeof workerMethods 
expose(workerMethods)

// index.ts
const pool = Pool(() => spawn<WorkerMethods>(new Worker('./worker')))

const res1 = await pool.queue(({ hugeFn }: WorkerMethods) => hugeFn())
// => 0.123456: number

const res2 = await pool.queue(...Array(500).fill(({ hugeFn }: WorkerMethods) => hugeFn()))
// => [0.23454, 0.89444, ...]: number[]

await pool.completed()
await pool.terminate()
```

**Comment by andywer** [comment]
Hey @rigwild. Sure, we could do that.

I would only argue that we should not make it a rest parameter, but allow passing a function or array as first argument. Otherwise we will later not have the chance to add an options argument if we need one.

**Comment by rigwild** [comment]
Good point! Did not think about options.

```ts
function queue<Return>(tasks: TaskRunFunction<ThreadType, Return>[], queueOptions?: QueueOptions): QueuedTask<ThreadType, Return>[]
```

**Comment by andywer** [comment]
The other question is, of course: It's a nice little gimmick, but is it worth overloading the API?

(Genuinely asking, esp. if anyone else can provide some feedback)

**Comment by andywer** [comment]
@rigwild Is that still something you would like to see implemented? You didn't reply to the last comment 😉

**Comment by rigwild** [comment]
> (Genuinely asking, esp. if anyone else can provide some feedback)

Oh sorry, I though you was waiting for comments from others 😅

I guess it's not that useful after all. The rest parameter would have been nice but as you said it might block you if you want to add new parameters 🤔
