### ISSUE TITLE
Observable and `Transfer`

### ISSUE THREAD

**Issue by pverscha** [andywer/threads.js#248]
Hi @andywer,

The documentation for this project demonstrates both Observables and `Transfer` separately but never combined. I'm working with large amounts of data that take some time to get passed from the worker to the main thread. I fixed this by residing to ArrayBuffers which don't need to be cloned and really speed things up.

However, I also like to report the processing status from the worker thread to the main thread, which I used to do by using an observable. Can you tell me how I can combine `Transfer` and observables? At this point I can only report progress without using ArrayBuffers, or only use ArrayBuffers without reporting progress.

**Comment by andywer** [comment]
Hey @pverscha!

This should work:

```js
expose(function doThings(arrayBuffer) {
  return new Observable(observer => {
    // do things…
    // when done:
    observer.next(Transfer(arrayBuffer))
    observer.complete()
  })
})
```

Tell me if that works for you. We can then update the docs :)

**Comment by pverscha** [comment]
Hi @andywer!

I didn't get back to you last week, but this does work :) Thank you very much!
