### ISSUE TITLE
Support async/await within the external script.

### ISSUE THREAD

**Issue by dannysmc95** [andywer/threads.js#253]
Hello again!

So I have been using this for a new project, which is loosely coupled with FaaS design, but one of the things I need is to be able to support async/await within the `expose` function, for example, I expose only one function, this function will call async functions, like sending an email or processing a PDF, but how would I define that the function returned is async? how would this work?

So:

I have the following:

```javascript
import { expose } from 'threads/worker';

expose({
    async foo(wait) {
        return Promise((resolve, reject) => {
            setInterval(() => {
                resolve(true);
            }, wait);
        });
    }
});
```

Essentially can I just define async functions within the expose function? and will they be handled correctly? or if I return a promise will it manage that correctly?

**Comment by andywer** [comment]
Hey @dannysmc95!

You can write the worker code in pretty much any way you like as long you don't try to pass functions or instances of classes.

So bottom line:

```js
import { expose } from 'threads/worker';
// You can import async functions from somewhere else

// You can declare async functions here

expose({
    async foo(wait) {
        // You can declare async functions here, too
        return Promise((resolve, reject) => {
            setInterval(() => {
                resolve(true);
            }, wait);
        });
    }
});
```

😉
