### ISSUE TITLE
Observe file upload progress 

### ISSUE THREAD

**Issue by glekner** [andywer/threads.js#259]
Suppose we have a worker that runs this code:

```js
 axios.post(UPLOAD_URL, ArrayBufferFile, {
            headers: {
              Authorization: `Bearer ${token}`,
            },
           // change setProgress to return the progress to the main thread
            onUploadProgress: (e) => setProgress(Math.floor((e.loaded / image.size) * 100)),
          })
          .then(() => setProgress(100))
          .catch((err) => setError(err));
      };
```

Can we possibly execute this function in a worker and observe the progress? since its an inner callback inside `axios`, I'm not sure how to implement this.

Also another question, can we spawn a worker in a file that is not `main.js`? lets say an inner route? and then leave that route and continue to subscribe to the same worker from a different route? I want to upload a file from a plugin inside a big app, and listen to the progress from a different route.

Thank you for your help!

**Comment by andywer** [comment]
Hey @glekner, sure you can.

You can return an observable that tracks the progress:

```js
// worker.js
import axios from "axios"
import { expose, Observable } from "threads/worker"

async function uploadFile(arrayBuffer, token) {
  return new Observable(observer => {
    axios.post(UPLOAD_URL, arrayBuffer, {
            headers: {
              Authorization: `Bearer ${token}`,
            },
           // change setProgress to return the progress to the main thread
            onUploadProgress: (e) => observer.next(Math.floor((e.loaded / image.size) * 100)),
          })
          .then(() => observer.next(100))
          .catch((err) => observer.error(err));
      };
  })
}

expose(uploadFile)
```

```js
// main.js

// ...
const uploadFile = await spawn(new Worker("./worker"))

uploadFile(fileContent, authToken).subscribe({
  next(progress) {
    // Do something with the `progress`
  },
  complete() {
    // Success
  },
  error(error) {
    // Handle error
  }
})
```

**Comment by andywer** [comment]
> Also another question, can we spawn a worker in a file that is not main.js? lets say an inner route? and then leave that route and continue to subscribe to the same worker from a different route?

Are we talking client or server code here? I assume server-side. Of course you can spawn a worker in a different module and import it from another module to use it their, too 😉

**Comment by glekner** [comment]
Hey @andywer , thanks for your help.
I'm talking about client side, lets say i'm working on a plugin that is inside a bigger app. can I mount the worker from the plugin, continue to navigate to other plugins in the app while the worker and upload continue without interference? (Its a react app so no refresh/full page reloads between pages of course)

**Comment by glekner** [comment]
Update, getting this error when trying to run an upload:

```
Error: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': (observer) => {
            axios__WEBPACK_IMPORTED_MODULE_0___default.a
                .post(url, image, JSON...<omitted>... } could not be cloned.
```

worker.js
```js
import axios from 'axios';
import { Observable } from 'observable-fns';
import { expose } from 'threads/worker';

async function uploadFile(image, token, url) {
  return new Observable((observer) => {
    axios
      .post(url, image, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
        // change setProgress to return the progress to the main thread
        onUploadProgress: (e) => observer.next(Math.floor((e.loaded / image.size) * 100)),
      })
      .then(() => observer.next(100))
      .catch((err) => observer.error(err));
  });
}

expose(uploadFile);
```

component.js
```js
  const uploadWithWorker = async () => {
    const uploadWorker = await spawn(new Worker('./cdi-upload-worker'));
    const reader = new FileReader();
    reader.onloadend = (ev) => {
      uploadWorker(Transfer(ev.target.result), token, UPLOAD_URL).subscribe({
        next(prog) {
          setProgress(prog);
        },
        complete() {
          console.log('UPLOADED');
        },
        error(err) {
          console.log('error', err);
        },
      });
    };
    reader.readAsArrayBuffer(image);
  };
```

**Comment by andywer** [comment]
I am not sure what `ev.target.result` is, but it seems as if it cannot be `.postMessage()`-ed.

Try this instead:

```diff
- uploadWorker(Transfer(ev.target.result), token, UPLOAD_URL)
+ uploadWorker(Transfer(image), token, UPLOAD_URL)
```

**Comment by glekner** [comment]
trying your code gives me this:
```js
error TypeError: Failed to execute 'postMessage' on 'Worker': Value at index 0 does not have a transferable type.
```

I think `ev.target.result` Transferrable, really stuck :(

**Comment by andywer** [comment]
I didn't try the code above myself, I just wanted to give you an idea. I didn't expect to see these kinds of errors, though 🤷‍♂️ 

So let's try these two things here:
1. Let's drop the `Transfer()` for now and only pass `uploadWorker(image, token, UPLOAD_URL)`
2. Try to `import { Observable } from "threads/observable"` (instead of importing from `observable-fns`)

**Comment by glekner** [comment]
Thanks for your time @andywer , before I put more time into this, I would be very happy if you could answer my previous question, ill try to make it more clear:

```js
// component.js
const uploadWorker = new Worker('/upload-worker');
uploadWorker.upload(file); 
...
```
If I unmount this component, meaning i'm navigating to another page while the upload is still happening, will the worker keep uploading the file? just without anyone listening to it? can I resubscribe to the same specific worker from another component if it keeps uploading?

Thanks a lot

**Comment by andywer** [comment]
Ohh, I misunderstood your question. Every observable returned from the worker will automatically be multicasted.

From the perspective of the returned observable it will look as if there is only one subscriber, no matter how many subscribers there are. If the last subscriber unsubscribes, however, the single subscription to the source observable will also be terminated.

This especially makes sense if you consider that "no subscribers" also means "no error handling". So back to your use case… Just keep an additional subscription that handles file upload errors, even when navigating between pages. This way the observable won't get terminated :wink:

**Comment by glekner** [comment]
Thanks for the info @andywer 

1) `const uploadWorker = new Worker('/upload-worker')` in two different files **won't** create a new thread and a new worker? they would just subscribe if its already created in one of them?
2) I guess i still have a problem then, having 1 component start the upload, while you navigate to the 2nd one, the 1st one will get unmounted and therefore no subscribers to the worker, it will get terminated. I still need to create/listen to it from a higher component in the tree.

**Comment by andywer** [comment]
1. Every call to `new Worker()` will create a new worker. It doesn't matter if it happens in one file or different ones. Just instantiate once and pass the reference around (store the result of `spawn()`, not the result of `new Worker()`, so you don't have to call `spawn()` repeatedly).
2. Just have one additional subscriber that does the error handling and that is not tied to the component state, but to some higher application state, potentially using a React context. The upload won't get terminated as long as you subscribe, but do not unsubscribe before the upload is done.

**Comment by andywer** [comment]
Closing for now.

**Comment by glekner** [comment]
Thanks for the info.
