### ISSUE TITLE
Project name is 'threads.js', actually calls fork()

### ISSUE THREAD

**Issue by rmzg** [andywer/threads.js#26]
See title.

**Comment by andywer** [comment]
Hmm... It's an isomorphic multithreading library, so I think the name is not really misleading. But I can also see your point here, since you might expect a more elegant approach than fork() for the node implementation.

What kind of threading implementation for node would you suggest?

**Comment by rmzg** [comment]
Well, https://www.npmjs.com/package/npool exists.

**Comment by andywer** [comment]
@rmzg Thanks. I will have a closer look at it as soon as I got some spare time ;)
