### ISSUE TITLE
commonJs modules broken

### ISSUE THREAD

**Issue by kissenger** [andywer/threads.js#260]
My node package is broken since update to v1.5+ --> I get error:

```Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:<myPath>\node_modules\threads\index.mjs```

I fixed it in my local files by requiring ```threads/dist```, but then I get the same error from ```geoTiff``` package which I don't want to mess with.  I've rolled back to v1.4.1 for now. 

Am I doing something wrong?

**Comment by andywer** [comment]
Hey @kissenger. A fix making the package consumable by node.js 14 ES modules was just shipped this week in threads.js v1.5.0.

Seems like it's broken now for node.js 14 if your code does not use ES modules 🙃

Looking into it…
