### ISSUE TITLE
Unsubscribing from observable in main thread does not cancel observable inside the worker.

### ISSUE THREAD

**Issue by Nerdinacan** [andywer/threads.js#262]
Thanks for a great library, it's got a flaw with returned observables though.

It is not possible to cancel/unsubscribe from an observable inside the worker without terminating the entire thread.

I built some nonsense in my app to get around this by building a subscription Map inside the worker and passing back a subscriptionKey so I could manually tell the worker to unsubscribe from its interior observable, but this seems like something that should be handled by the transfer layer, which is probably already packing and unpacking the payloads, yeah?

```javascript

// main page

import { Observable, from } from "rxjs";
import { tap, take, finalize, map } from "rxjs/operators";
import { spawn, Thread, Worker } from "threads"

let _thread;
async function getThread() {
    if (!_thread) {
        _thread = await spawn(new Worker("./MyWorker"))
    }
    return _thread;
}

export async function listenToQuery() {
    const cacheThread = await getThread();

    // converting to rxjs just so I can use take/finalize
    const obs$ = from(cacheThread.monitorQuery());

    return obs$.pipe(
        take(3),
        finalize(() => {
            console.log("I'm done now, corresponsing observable inside worker should unsubscribe now too, but it doesn't");
        }
    );
}


// MyWorker.js

import { expose } from "threads/worker"
import { interval, map } from "observable-fns";

expose({
    monitorQuery: () => interval(2000).pipe(
        map(val => {
            console.log("in worker", val);
            return val;
        })
    )
});
```

**Comment by andywer** [comment]
Hey @Nerdinacan! Thanks for sharing.

I think first I need to make sure we are talking about the same thing.

> It is not possible to cancel/unsubscribe from an observable inside the worker without terminating the entire thread.

This sentence is a double negative, almost triple negative, so I am gonna make sure I got the message right.

~~You say that (in a worker) unsubscribing from a an observable returned by a worker function will lead straight to the worker's termination. Correct?~~

I think I just got it. The issue title says it, the issue description says something else, unfortunately 😅

You can unsubscribe from the worker function's returned observable in the master thread, but the original observable in the worker thread will not be notified about the cancellation of the subscription. Right? 🙂

**Comment by andywer** [comment]
So we can see the issue here, where cancelling an observable that proxies an observable returned in the worker is handled: https://github.com/andywer/threads.js/blob/944bc8c83eaf00a09f2a5f2a21ca723966450ee5/src/master/invocation-proxy.ts#L75

On cancellation the proxy observable in the master thread only stops handling the messages sent by the worker, but does not send a message to the worker to inform it that the subscription has been cancelled.

So we need to send such a message and then handle it in the worker.

**Comment by andywer** [comment]
@Nerdinacan I prepared a fix. Would you like to test the fix?

```
npm install threads@1.6.1-proxy-unsubscribe
```

**Comment by Nerdinacan** [comment]
> Hey @Nerdinacan! Thanks for sharing.
> 
> I think first I need to make sure we are talking about the same thing.
> 
> > It is not possible to cancel/unsubscribe from an observable inside the worker without terminating the entire thread.
> 
> This sentence is a double negative, almost triple negative, so I am gonna make sure I got the message right.
> 
> ~You say that (in a worker) unsubscribing from a an observable returned by a worker function will lead straight to the worker's termination. Correct?~
> 
> I think I just got it. The issue title says it, the issue description says something else, unfortunately 😅
> 
> You can unsubscribe from the worker function's returned observable in the master thread, but the original observable in the worker thread will not be notified about the cancellation of the subscription. Right? 🙂

That's correct.
Thanks for the amazingly quick response. I'll take a peek!

**Comment by Nerdinacan** [comment]
I'll keep playing with it, but looks good so far!

Thanks a ton!

**Comment by Nerdinacan** [comment]
Been using this several days on a project I'm working on, works great now.

I can switchMap from the main thread and watch the interior observable unsubscribe and resubscribe to the new passed stuff. It's great.

Thanks again!
