### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist' is not defined by "exports"

### ISSUE THREAD

**Issue by sanex3339** [andywer/threads.js#265]
With `1.6.1` version i got
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist' is not defined by "exports" in /foo/bar/javascript-obfuscator/node_modules/threads/package.json`

error. 

I'm using `commonJs` modules.

**Comment by andywer** [comment]
Hey @sanex3339. Are you trying to import from `threads/dist/*`?

**Comment by sanex3339** [comment]
Yes:
```
import { spawn, Thread, Worker } from 'threads/dist';
```

**Comment by andywer** [comment]
Try it without the `/dist` instead:

```js
import { spawn, Thread, Worker } from 'threads';
```

**Comment by sanex3339** [comment]
Looks like it has worked

**Comment by andywer** [comment]
Awesome! Feel free to re-open if it turns out to not work as well as it should 😉

**Comment by sanex3339** [comment]
Thank you!
