### ISSUE TITLE
Passing Moment.js object to worker results in DataCloneError error 

### ISSUE THREAD

**Issue by crazywako** [andywer/threads.js#267]
Environment: Node v.12.13.1
Threads version: "^1.6.2"

Passing Moment.js object to worker results in DataCloneError error 

**Error:** 
```
(node:16345) UnhandledPromiseRejectionWarning: DataCloneError: function (number) {
            var b = number % 10,
                output =
                    toInt((number...<omitted>... } could not be cloned.
    at Worker.postMessage (internal/worker.js:223:23)

```

**Code:**

```js
import Moment from 'moment' // https://momentjs.com/

const createReportWorker = await spawn(new Worker('../app/_createReportWorker'))
const report = await createReportWorker.createReport({startDate: Moment('2020-01-01')}) // This line produces the above error.

```

I did bypass it by providing that startDate as  a string instead of Moment object, but would be nice if it would work out of the box.

**Comment by andywer** [comment]
Hi, @crazywako.

That's expected behavior. You can only pass values to the worker that `postMessage()` can handle. Use [custom serializers](https://threads.js.org/usage-advanced#custom-message-serializers) to transparently serialize/deserialize your moment.js date instances 😉
