### ISSUE TITLE
Waiting for a specific task to complete

### ISSUE THREAD

**Issue by aya1337** [andywer/threads.js#276]
Hello andy, I noticed that there's only [a way to check if the entire pool has no tasks pending](https://threads.js.org/usage-pool#waiting-for-tasks-to-complete)
If I have a pool where each worker has several exposed functions (where one can take a very long time and the other a very short time) and the pool size for an example is **5** workers.
If I use the very taxing function first (assigned to worker1) and then a very fast one (assigned to worker2). The only way for me to know if the very fast function has ended is to wait for the entire pool to be free which is not an ideal thing since one exposed function can last 2 minutes and the other 2 seconds. 
Would something like this be possible? 
```js
const task = pool.queue(multiplierWorker => multiplierWorker(2, 3))
await task.completed() //await task.settled()
```
Or any other way to know if a certain task has ended.

**Comment by andywer** [comment]
Ha! I think this is already supported, yet the way it is implemented might make it hard to discover. I think this should work: `await task`

Maybe the API design is "too smart for its own good" here 😉

**Comment by aya1337** [comment]
Ooooo fancy :D
*Documentation should mention it*
