### ISSUE TITLE
Request: Build ES6 version?

### ISSUE THREAD

**Issue by jmstein** [andywer/threads.js#29]
It looks like the code is written with ES6 modules but the built version is using babel to transpile down and uses commonjs modules to support that.  As people are adopting newer versions of ES, would it be useful to build an ES6 module as well?

**Comment by andywer** [comment]
Hey @jmstein. You mean like rollup's `jsnext:main` prop in `package.json` or like node's `.mjs`?
(Latter one not yet supported by any stable node version AFAIK)

The `jsnext:main` shouldn't be a problem, I think.

**Comment by andywer** [comment]
Closing it for now, since it's currently not a priority. Feel free to open a PR, anyway 😉
