### ISSUE TITLE
Can't resolve 'child_process' in tiny-worker/lib

### ISSUE THREAD

**Issue by EvgenyRodygin** [andywer/threads.js#291]
Hi and thanks for your work. The library saves a lot of effort on building isomorphic apps

I have an issue completely similar to the one described in #183. Even the configs are very similar.
I've completed all the steps but after adding all the modules to the IgnorePlugin I still get errors.
Webpack considers node packages missing.
```
Error: Cannot find module 'os'
    at webpackMissingModule (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/implementation.node.js?:9:45)
     at eval (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/implementation.node.js?:9:122)
     at Module../node_modules/threads/dist-esm/master/implementation.node.js
     at __webpack_require__ 
     at eval (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/implementation.js?:6:78)
     at Module../node_modules/threads/dist-esm/master/implementation.js
     at __webpack_require__
     at eval (webpack://%5Bname%5D.js/./node_modules/threads/dist-esm/master/index.js?:4:73)
```
I use target: "node". Is there any info I can provide to resolve this?

**Comment by andywer** [comment]
Hey @EvgenyRodygin! Can you provide your webpack config, too?

**Comment by EvgenyRodygin** [comment]
Sure.
Simplified it:
```
const path = require("path");
const webpack = require("webpack");
const ThreadsPlugin = require('threads-plugin');

commonConfig = {

  resolve: {
    extensions: ["*", ".js", ".jsx"]
  },

  target: "node",

  entry: {
    "make_preview": ["./src/nodejs/make_preview.js"]
  },

  output: {
    library: "[name].js",
    libraryTarget: 'commonjs2',
  },

  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|src\/libs)/,
        use: [
          {
            loader: "babel-loader",
            options: {
              cacheDirectory: true
            }
          }
        ]
      },
    ]
  },

  plugins: [
    new ThreadsPlugin(),
    new webpack.NormalModuleReplacementPlugin(
      /^bindings$/,
      path.resolve("src/nodejs/bindings.js"),
    ),
    new webpack.IgnorePlugin(/(tiny-worker|path|tty|crypto|fs)/)
  ],

  output: {
    path: path.resolve("build"),
  }

};
```

Here is also .babelrc in case:
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["module-resolver", {"root": ["."]}],
    ["@babel/plugin-transform-runtime",
      {
        "helpers": false,
        "regenerator": true
      }
    ]
  ]
}

**Comment by EvgenyRodygin** [comment]
Ok. I found out what is the root of the error. I've been accidentally importing "threads" instead of "threads/worker" in worker-files.
The thing is it all worked in the browser build for some reason which completely fooled me. If there is a way to give a warning or just remove all unnecessary fields from the top-level namespace, IMO that would be a preferable behavior. Had quite a painful experience with this little issue :)
Thanks for your work again. Closing.

**Comment by andywer** [comment]
Nice to see that you could solve it, but I can see how confusing that may be.

> or just remove all unnecessary fields from the top-level namespace

What fields on the top-level namespace are in your opinion unnecessary? 😉

**Comment by EvgenyRodygin** [comment]
@andywer
> What fields on the top-level namespace are in your opinion unnecessary?
I might be missing something but to me "expose" looks unnatural in the main namespace (import from "threads").
Especially taking into account that it actually works if being called from the worker-thread.
Haven't seen such imports in any of your examples.

**Comment by andywer** [comment]
So the basic idea at the time was to make the main entrypoint export everything, whereas the worker entrypoint only exports the worker-relatived things as they are relatively small, so you can have small worker bundles while the worker code is small enough and easily dead-code-eliminated from the main bundle.

Meanwhile I found the real origin of the error, though. A bug / unintuitive configuration behavior in the `threads-plugin`: https://github.com/andywer/threads-plugin/pull/24

I will release a bug fix and then we can just import the main entrypoint from workers if we like 😉

**Comment by EvgenyRodygin** [comment]
> I will release a bug fix and then we can just import the main entrypoint from workers if we like
Cool! Thanks for the quick resolution!
I'm guessing that the [docs](https://github.com/andywer/threads-plugin#target) are a little outdated in this matter as possible values are anything falling under the /\bnode\b/ regex.

**Comment by andywer** [comment]
Ohh, right. Updated the readme 👍
