### ISSUE TITLE
Misleading timeout log/message

### ISSUE THREAD

**Issue by GeorgiJefferski** [andywer/threads.js#292]
**current line:**
https://github.com/andywer/threads.js/blob/7bf8ed98fec04125b9c34b13eeaee8236e473f44/src/master/spawn.ts#L149

**should be corrected to:**
const initMessage = await withTimeout(receiveInitMessage(worker), options && options.timeout ? options.timeout : initMessageTimeout, `Timeout: Did not receive an init message from worker after ${options && options.timeout ? options.timeout : initMessageTimeout}ms. Make sure the worker calls expose().`)

**or refactored, e.g.:**
const timeout = options && options.timeout ? options.timeout : initMessageTimeout
const initMessage = await withTimeout(receiveInitMessage(worker), timeout, `Timeout: Did not receive an init message from worker after ${timeout}ms. Make sure the worker calls expose().`)

**Comment by andywer** [comment]
Good point. Fixed in #293 😉

**Comment by GeorgiJefferski** [comment]
Thank you!
