### ISSUE TITLE
Cannot transfer OffscreenCanvas object to worker function

### ISSUE THREAD

**Issue by yrq110** [andywer/threads.js#299]
since OffscreenCanvas is a kind of [transferable object](https://developer.mozilla.org/en-US/docs/Web/API/Transferable):

```
The ArrayBuffer, MessagePort, ImageBitmap and OffscreenCanvas types implement this interface.
```

so i thought  transfer OffscreenCanvas to worker by using `Transfer` in threads should work:

```js
import { Transfer } from 'threads'
const offscreenCanvas = canvas.transferControlToOffscreen()
await myThreadsWorkerFunc(Transfer({ canvas: offscreenCanvas, payload: ..}, [offscreenCanvas]))
```

but then i got this error:

```
Type 'OffscreenCanvas' is not assignable to type 'Transferable'.
Type 'OffscreenCanvas' is missing the following properties from type 'MessagePort': onmessage, onmessageerror, close, postMessage, start
```

**Comment by andywer** [comment]
Hey @yrq110,

thanks for reporting. That's mighty weird. We only re-use the `OffscreenCanvas` type that comes with the built-in TypeScript DOM types and that seems to include the `OffscreenCanvas`, too:

![image](https://user-images.githubusercontent.com/1842462/91876132-a796d000-ec7c-11ea-9429-8cf9f3007355.png)

What do you see when you inspect the `Transferable` type? Or maybe you are running an outdated TypeScript version?

**Comment by yrq110** [comment]
Thanks for reply. @andywer 

You are right. The TS in my project is outdated version `3.7.3`. This issue has gone after update TS to version `3.9.7`.

And the reason i see the right content when inspect the `Transferable` before is that it shows the type content from VSCode built-in TS lib
