### ISSUE TITLE
Uncaught Exception - out of memory in FireFox

### ISSUE THREAD

**Issue by DemersM** [andywer/threads.js#30]
I encounter  uncaught exception: out of memory errors for jobs in a pool that returns json. The pool handle 21 jobs, but some jobs throw that error randomly. Some returned json are big (8mb and more), but that's not always the biggests that throw the error... 

The error occurs only in FF, not in Chrome or IE.

```
var Pool = require("threads").Pool;

var pool = new Pool();
pool
    .on("finished", function() {
        pool.killAll();
    });

var loadRemoteZippedJson = function(url) {
    var job = pool.run(
        function(url, done) {
            importScripts('./jszip.min.js');
             var xhr = new XMLHttpRequest();
             xhr.open('GET', url, true);
             xhr.responseType = "arraybuffer"
             xhr.onreadystatechange = function() {
                    if (xhr.readyState == 4) {
                        var zip = new JSZip(xhr.response);
                        var c = zip.file(url.split("/")[1]).asText();
                        done(JSON.parse(c), url);
                    }
               }
               xhr.send(null);
         }
    ).send(url);

    job.on("done", function(c, url) {
        doSomething(c, url);
    });
}
```

**Comment by DemersM** [comment]
After, some tests, I realize I have the problem with plain web worker api not using threads.js. This issue might be related to possible memory leak in firebug because the problem happen only when firebug is open.

I am closing this issue because it was not related to threads.js

**Comment by andywer** [comment]
Alright 👍 I appreciate self-closing issues ^^
