### ISSUE TITLE
Initialization timeout affected by slow connection

### ISSUE THREAD

**Issue by EvgenyRodygin** [andywer/threads.js#302]
Hi Andy and thanks for your work again!
I'm experiencing an issue when the library refuses to initialize a worker with the following message:
`Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose()`

This happens in a case when I simultaneously spawn several not so small (~1mb) workers and turn on Network Throttling in Chrome.
It looks like the library starts the countdown when the scripts haven't been downloaded yet. Can we do something about this?
E.g. start the timer when the script is already downloaded. I believe this might affect a serious amount of users.

**Comment by andywer** [comment]
Sorry for the late response, @EvgenyRodygin!
I saw the issue, wanted to respond, wanted to investigate myself first and then didn't find the time…

That's a quite interesting observation. I fear there is no better way to start counting after the worker script has been fetched. I have a few other suggestions, though:

1. You can pass a custom `timeout` in `spawn()`'s options. You could set it to something more appropriate, based on the current network connectivity (maybe use https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API).
2. Preload the worker script by adding a `<link rel="preload" href="$URL" as="worker" />` to your page's `<head>`

**Comment by EvgenyRodygin** [comment]
Oh I missed the comment. Thanks for the suggestions!
I don't work on the project utilizing the library anymore but I might start using it in another one soon.
Preloading the worker seems like a good idea.
