### ISSUE TITLE
Worker is not exported correctly.

### ISSUE THREAD

**Issue by crubier** [andywer/threads.js#303]
In a TS project, if I do this:

```typescript
import * as threads from "threads";

console.log(threads);
```

I get this

```
    { __esModule: true,
      config: { get: [Function: get], set: [Function: set] },
      defaults: { pool: { size: 12 } },
      Pool: { [Function: Pool] spawn: [Function] },
      spawn: [Function: spawn],
      default:
       { config: { get: [Function: get], set: [Function: set] },
         defaults: { pool: [Object] },
         Pool: { [Function: Pool] spawn: [Function] },
         spawn: [Function: spawn],
         Worker: [Function: Worker] } }
```

As we see, `Worker` is not exported directly, it's only in `default`

Which explains why I can't `import { spawn, Pool, Worker, ModuleThread } from "threads";` (it gives me `Worker = undefined`)

**Comment by crubier** [comment]
Workaround for now:


```typescript
import threads from "threads";
const { spawn, Pool, Worker, ModuleThread } = threads;
```

**Comment by andywer** [comment]
Thanks for reporting, @crubier. What version of node.js and threads.js are you using and what's your TypeScript module target (do you output ESMs or CJS)?

I just quickly tried the latest version on runkit (https://npm.runkit.com/threads, make sure to select node 12) and at least when consumed as a CommonJS module it looks fine.

![image](https://user-images.githubusercontent.com/1842462/93709569-7b65c500-fb3f-11ea-9743-83ea15a4b1d2.png)

**Comment by andywer** [comment]
Pinging @crubier.

**Comment by crubier** [comment]
I don't know actually, I was not able to reproduce my bug. I was in a weird monorepo configuration with pnpm, and now I think the problem is solved on my side. I guess it was just a weird fluke / corner case, we can probably close.

**Comment by andywer** [comment]
Alright, then let's close for now 😉
