### ISSUE TITLE
The class (prototype) of the exception thrown in worker is not preserved

### ISSUE THREAD

**Issue by ivan-aksamentov** [andywer/threads.js#304]
Hi Andy,

I just noticed that if I throw something other than `Error` inside worker, the class of the thrown object is not preserved when it crosses the process boundary.

For example, if I throw `MyError` derived from `Error`:

```js
// worker.js
class MyError extends Error {}

const worker = () => throw new MyError("Hello")

expose(worker)

```

these checks return incorrect results:

```typescript
// main.ts
try {

  // invoke worker() here using threads.js

} catch(error) {
  error instanceof MyError // `false`. Expected `true`

  error instanceof Error   // `true`. I think this one is technically correct, 
                           //  but, together with the previous, not really.

  error.constructor.name   // `'Error'` (string). Expected `'MyError'`.
}

```

I understand that this is due to serialization-deserialization necessary for structured cloning to work, but would be nice if classes were preserved (or rather re-created), as this is a critical part of any decent error handling. Bonus points for preserving the whole class hierarchy.
I am currently stuck with error handling in our app, because I don't know how else to distinguish the  error objects without causing too much havoc. Cannot hardcode the messages inside error objects due to the way internationalization is set up, and also we have some errors carrying a payload, which is different for different types. Therefore I'd prefer a typesafe Typescript solution (`instanceof`).

---

Here are some of the things I found on the internet about how to restore object's class during deserialization:
 - https://stackoverflow.com/questions/38922990/re-associating-an-object-with-its-class-after-deserialization-in-node-js
 - https://essentialjavascript.wordpress.com/2016/02/11/deserialize-json-to-instance-of-javascript-class

Some of the solutions may include:
 - `Object.getOwnPropertyDescriptors()` - not yet well supported, but may be transpiled/polyfilled with Babel
 - `Object.setPrototypeOf()` - slow, causes deoptimization when accessing the object (which is fine for Errors, unless it also touches other objects)
 - `Object.create()` - should be fine? We create an object from scratch, right?
 - `obj.__proto__ `

I'd be glad to help with the implementation and testing!

---
Update:

Just found where the "type erasure" happens:

https://github.com/andywer/threads.js/blob/9009590642d16c9cdb46cd05e1e0e047c1815b16/src/serializers.ts#L49-L64

Would be nice if deserialization would not assume the `Error` type and this particular set of properties, but rather carried over the prototype and all the properties somehow.

**Comment by andywer** [comment]
@ivan-aksamentov Sorry for the late response!

I don't think we can fix that on the library's side of things. In order to "restore" the objects' prototypes after deserialization, we would need to know all your classes. That's what the serializers are for.

Btw, generally speaking it's a brittle practice to rely on `instanceof` anywhere really in JavaScript. The reason is that `node_modules/` can contain multiple versions of the same package for different sub-dependencies. So you end up with dependency A using package X in version 1 and dependency B and your own code might be using package X in version 2.

That means that you now have two versions of X at runtime, each with its own set of static objects, functions, classes, … If A now runs `new X()` and returns/throws it and you check the result in your code using `instanceof X`, you will always get a `false`, since your X is a different X than what dependency A has, due it's different version of the X package.

Alternative: Not super pretty, but I usually just set a custom `name` on my custom errors and check that then instead of `instanceof`. This way you always get predictable behavior, no matter in what context and weird dependency trees your code ends up in.

To your original question: I think you need to create a custom serializer for your error classes.

**Comment by ivan-aksamentov** [comment]
Hi @andywer,

 > I don't think we can fix that on the library's side of things. In order to "restore" the objects' prototypes after deserialization, we would need to know all your classes. 

We don't need to know all the classes. We just need to restore the object prototype as it was. More precisely, we need to make sure we don't erase the prototype when transferring (lines 60 and then 51 of the snippet I posted). This will allow all the built-in prototype-based mechanisms to work, including (but not limited to) `instanceof`.

There are 4 known working possible implementations I mentioned. There might be more. None of them involve list of all classes, as you see.

I just don't know where to stick them into `threads.js`, maybe on line 51? I just thought you know it better.

 > I usually just set a custom name on my custom errors and check that then instead of instanceof

Well, then you just reimplement a limited version of `instanceof` in userspace. On high level, that's what `instanceof` is doing - is checking for the value of `__proto__` property in the prototype **hierarchy** (in reality, it has changed a bit in newer version and, it's doing a bit more more than that).

Again, same as you don't need to know all the possible values of your `name` property, you don't need to know anything about the prototype, you just need to carefully copy it over.

In Typescript `instanceof` also provides the correct type inside the conditional (see the example). Cannot do this easily in userspace without very ugly casts. I my case, the type is needed to safely access additional properties on the custom error object.

> it's a brittle practice to rely on instanceof anywhere

I did not understand that. I only need to check for my own error types, so node_modules are not involved. But if that's a problem for other users, maybe we can make the prototype restoration optional? (especially that it might have a little impact on performace in cases then the worker throws)

Also, `instanceof` relies on comparison with whatever you are importing, so if there's version mismatch between thrown and imported, as you've described, then your `name`-property-based solution is as broken as prototype-based, because they are pretty much the same - a property comparison followed by a cast.

> I think you need to create a custom serializer for your error classes

I did not find a way of doing this. I see that you can do this with message body. How I can make it work for all the thrown errors? It's definitely not feasible to write separate serializers for every error class.

If we can swap the serializer on runtime, then the prototype restoration can be made truly optional. Can even be shipped as another npm package if needed.

**Comment by andywer** [comment]
I think we are talking past each other here 😉

> More precisely, we need to make sure we don't erase the prototype when transferring (lines 60 and then 51 of the snippet I posted)

There is a good reason we do that: The structured clone algorithm that the worker's `postMessage()` uses under the hood cannot serialize anything with a prototype on it. So we actually cannot send something between threads that has a prototype.

> you don't need to know anything about the prototype when (de)serializing, you just need to carefully copy it over

How would you serialize the prototype given the constraint that `postMessage()` will throw if try to send a function, an object with a prototype or any object containing something like this? 😉

> There are 4 known working possible implementations I mentioned. There might be more. None of them involve list of all classes, as you see.
> I just don't know where to stick them into threads.js, maybe on line 51? I thought you know it better.

None of these four snippets applies to this universal use case. If you want to restore the prototype (which is the class of that object and a class in JS is basically only a function) you need to have a reference to that class.

> Also, instanceof relies on comparison with whatever you are importing, so if there's version mismatch between thrown and imported, as you've described, then your name-property-based solution is as broken as prototype-based, because they are pretty much the same - a property comparison followed by a cast.

Nope. My solution involves a string comparison only and that will pretty much always work. You don't have to take my advice, though.

> It's definitely not feasible to write separate serializers for every error class. How I can make it work for all the thrown errors?

You don't necessarily need to write one serializer per class. You can also have one for all of your classes.

Find the serializer docs here: https://threads.js.org/usage-advanced#custom-message-serializers
