### ISSUE TITLE
Worker node process pid and migration for updated node and threads releases.

### ISSUE THREAD

**Issue by ascandal** [andywer/threads.js#305]
Migrating to Node 12 and threads.js 1.6.3.

### In this setup the worker is spawned and initiated 

```
this.worker = await spawn<WorkerModule<OptimizerWorkerKeys>>(new Worker(worker));
this.worker.create(args.model, args.config, args.simulation);

const pid = this.getWorkerPid();
```

### where getWorkerPid is

```
private getWorkerPid(): number {
    const symbols = Object.getOwnPropertySymbols(this.worker);
    const workerSym = symbols.find((symbol) => String(symbol) === 'Symbol(thread.worker)');

    return get(this.worker[workerSym], 'child.pid');
}
```

### Then the process can be aborted using like so

```
process.kill(pid);
```

## Questions

* Is this the correct way to manage and abort the node worker processes?
* Are there any migration instructions for threads.js from 1.0.0-beta.8 to 1.6.3?
  * Any thing specific to Node 12?
* Node 14 is scheduled to be made LTS in October 2020. Any expected compatibility or migration issues with Node 14?

**Comment by andywer** [comment]
Hey @ascandal. Sorry for the late reply.

Why don't you just use `Thread.terminate(this.worker)`? 😉

**Comment by ascandal** [comment]
@andywer Ah yes. I can however I want the process to continue running even when the browser is closed and reopened. Therefore I need to save some hook to the worker process in the database ( in this case mongo).

**Comment by ascandal** [comment]
@andywer Turns out that the above method I was using does not work any longer. Since node 12 `worker_threads` do not have a process id any longer. They do have a threadId, however I do not see any way to terminate a thread given its `threadId`.

Therefore it appears the only way is to maintain the worker thread references in a in a long running service on the server.

For my particular case, the application is Angular 9, with nestjs 6.8.5.

I found that I need to keep a list of the active worker references in the main server. This is the only way I see able to maintain a long running reference to the worker. However this seems like a fragmented code way of doing things.

Wondering if there is a best practice in this scenario for managing the workers in an angular application.

**Comment by ascandal** [comment]
Turns out I can store worker references outside the reference scope injected service in the server.

```
export const workerRefs: { [id: string]: any } = {};

@Injectable({ scope: Scope.REQUEST })
export class SomeService implements OnModuleDestroy, OnApplicationShutdown {
````

**Comment by andywer** [comment]
@ascandal So it was more of an Angular issue, but nice to hear you found a solution!

**Comment by ascandal** [comment]
@andywer Yeah. Problem solved for now. However, again maintaining the worker references outside the service still seems fragmented to me. Ideally I think it would be cool to be able to terminate workers given threadId.

Anyway thanks for your help.

**Comment by andywer** [comment]
I'm gonna close this issue for now.

I can't really help with Angular as I haven't touched it in years. Maybe it's a silly question, but why can't you just move the worker references into the service as an instance variable?
