### ISSUE TITLE
Is there a generic postMessage interface?

### ISSUE THREAD

**Issue by kevzettler** [andywer/threads.js#311]
Hello I have some existing worker code that uses the `worker.postMessage` `self.addEventListener('message'` events I would like to migrate to threads.j for isomorphic purposes with node.js. The documentation has no examples of using `worker.postMessage` interface and uses the `expose` RPC like interface. 

Is there hidden `postMessage` access or can you provide an example of how to make a generic `postMessage` and listener interface using the `expose` method?

**Comment by andywer** [comment]
Hey @kevzettler!

The worker that you pass to `spawn()` will always be a worker compatible with the web worker API. You can call its `.postMessage()` method manually.

In the worker you can then safely ignore the `expose()` function and manually run your `self.addEventListener('message')` instead.

The gotcha: I never tried it and I think webpack might not work as expected. Not sure, though. Maybe you just want to give it a try and share your findings here? 🙂

**Comment by andywer** [comment]
@kevzettler So your specific use case was to migrate existing (non-threads.js) code to threads.js gradually, that's why you want to expose the low-level functions?

PS: Are you running the code in node.js, browsers or both?

**Comment by kevzettler** [comment]
@andywer 
> @kevzettler So your specific use case was to migrate existing (non-threads.js) code to threads.js gradually, that's why you want to expose the low-level functions?

correct. 

> PS: Are you running the code in node.js, browsers or both?
I am now running on node.js and browser, with plans for electron in the future. 

I had previously only been working in the browser environment but wanted to reproduce the same worker code on the server. 

`threads.js` appeared to be the simplest migration path because of its robust multi-environment implementation abstraction with node,browser and tiny-worker from https://github.com/andywer/threads.js/tree/master/src/worker

I am not using any of the other abstractions that threads.js provides like Observerables or pooling. I think there may be value to publish that core worker implementation as its own independant module.
