### ISSUE TITLE
Webpack: ModuleNotFoundError: Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Christilut** [andywer/threads.js#314]
```
Uncaught Error: Module build failed (from ./node_modules/threads-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'C:\Users\Alpha\workspace\rekordcloud\node_modules\electron'
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\neo-async\async.js:2830:7
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\neo-async\async.js:6877:13
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Alpha\workspace\rekordcloud\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Alpha\workspace\rekordcloud\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Alpha\workspace\rekordcloud\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\Alpha\workspace\rekordcloud\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
```

I'm using Threads.js in Electron with webpack (electron-forge). It's worked completely fine until suddenly it completely broke when I added one line (seemingly unrelated to threads.js).
It really feels like this is a circular dependency problem because uncommenting a totally unrelated line just fixes the build error. But the error is always in the threads-plugin so I don't know what exactly the problem is.

I've already tried to get find and get rid of all my circular depedencies with madge but it had no effect. I've tried a bunch of workarounds with `require` and another workaround to import all my threads.js modules from a single file but always the same error.
I've tried setting my webpack target to `node` but that just breaks things more.

There isn't really much code to share in this case... I have this line in a few files:
```
import { spawn, Thread, Worker } from 'threads'
```
Now when doing the exact same thing in another file, I get the above error. Removing this line in the last file and the error disappears.

Any idea how I can debug this?

**Comment by andywer** [comment]
Sorry for the late response!

This usually happens if you import from `threads` directly in your worker code and not from `threads/worker`, but only in some Electron setups.

My best guess is that webpack is told that it's a node.js runtime, but no one told webpack that the web view code is not.

**Comment by Christilut** [comment]
Thanks, got it fixed. It might have been adding `target: 'electron-node-worker'` to the threads-plugin or maybe I did import from `threads` instead of `threads/worker` last time.
