### ISSUE TITLE
Always receive TransferDescriptor unlike the docs

### ISSUE THREAD

**Issue by atifsyedali** [andywer/threads.js#320]
Currently, the docs for Transfer objects hint at wrapping an ArrayBuffer and passing that to a worker, which receives the argument in the form of an ArrayBuffer that you then create an Uint8Array view out of. For example, 

```
// master.js
import { spawn, Transfer, Worker } from "threads"

const xorBuffer = await spawn(new Worker("./workers/arraybuffer-xor"))
const resultBuffer = await xorBuffer(Transfer(testData), 127)
```

and 

```
// workers/arraybuffer-xor.js
import { expose, Transfer } from "threads/worker"

expose(function xorBuffer(buffer, value) {
  const view = new Uint8Array(buffer)
  view.forEach((byte, offset) => view.set([byte ^ value], offset))
  return Transfer(buffer)
})
```

However, when I try this example, I never receive an ArrayBuffer in the worker. Instead I receive a TransferDescriptor, which doesn't work by wrapping it in a Uint8Array, so I actually have to end up doing:

```
// workers/arraybuffer-xor.js
import { expose, Transfer } from "threads/worker"

expose(function xorBuffer(buffer, value) {
  const view = new Uint8Array(buffer.transferables[0]); // <------- have to use .transferables[0]
  view.forEach((byte, offset) => view.set([byte ^ value], offset))
  return Transfer(buffer)
})
```

1. Am I doing something wrong? Is copy-by-reference is even working or is it just doing copy-by-value on the entire TransferDescriptor?

2. If not, should the docs be updated?

**Comment by andywer** [comment]
Hey @atifsyedali. Thanks for reporting!

I have got to look into that. Your code looks about correct on first glance. Since something doesn't seem to be right with the `Transfer()`, I am not sure if it just copies the whole transfer descriptor – it shouldn't, though.

Quick question: You are running the code in the browser, I assume?

**Comment by atifsyedali** [comment]
@andywer That's correct...tried with both latest Chrome and latest Firefox

**Comment by atifsyedali** [comment]
So it turns out that the line transferable.js#11 (method name isTransferDescriptor):

`return thing && typeof thing === "object" && thing[$transferable];`

Returns undefined for a valid TransferDescriptor, which transfers the whole thing by value then. The check `thing[$transferable]` returns undefined. Not sure why ... the property does not seem to be enumerable so I can't check for equivalency of the symbol either. Can we use a plain string key for identification instead? Something like `____THREADS_JS_TRANSFERABLE`?

**Comment by atifsyedali** [comment]
Okay, I realized my mistake. I was doing 

`import { Transfer } from "threads/worker"` 

in both the main thread and worker thread. The above line should be how it is in worker thread, but in the main thread, it should be:

`import { Transfer } from "threads"` 

The symbols are different for `"threads"` and `"threads/worker"` imports.

Sorry for inconvenience. Closing.
