### ISSUE TITLE
Parcel + Storybook

### ISSUE THREAD

**Issue by Zodiase** [andywer/threads.js#335]
If I'm reading the docs correctly, with Webpack (which Storybook uses) I'd want to import `Worker` directly from `"threads"`, while with Parcel (1) I should be using the global `Worker` class so as to not break the support from Parcel.

My project is in TypeScript, built with Parcel (1), but tested with Jest and Storybook. Storybook uses Webpack and I managed to get a Web Worker demo with the help from `threads-plugin`. For which I need `import { spawn, Thread, Worker } from 'threads';` in my code.

How can I make it work with Parcel now without breaking the Storybook (Webpack)?

**Comment by andywer** [comment]
Hey @Zodiase, great question!

Fortunately I myself have run into that before in an open source project and created a (quick & dirty) workaround for that case:

* Find the storybook's webpack config here: https://github.com/satoshipay/solar/blob/master/.storybook/webpack.config.js
* We made some minor modifications to webpack's worker-plugin and published a fork: https://www.npmjs.com/package/@satoshipay/worker-plugin#fork-changes

You can then use the global `Worker` in webpack, too.
We should probably document those known hacks & workarounds somewhere…

Disclaimer: Be aware that this workaround is one year old and hasn't been tested with webpack 5 or parcel 2.
