### ISSUE TITLE
[QUESTION]: Transfer

### ISSUE THREAD

**Issue by simplecommerce** [andywer/threads.js#338]
Hi,

I am trying to use the Transfer feature but I don't seem to understand it.

If I have a Blob or regular Array, how would I pass it to the Transfer object to return it?

I keep getting the transfer error because of the type when I try to use it.

Sorry if I am being unclear.

**Comment by andywer** [comment]
Did you solve it already, @simplecommerce?

**Comment by simplecommerce** [comment]
@andywer Yes sorry, I don't know what I did differently from yesterday but it works fine now! Thanks!
