### ISSUE TITLE
[QUESTION]: Pools and Observables

### ISSUE THREAD

**Issue by simplecommerce** [andywer/threads.js#339]
Hi, 

My question is based on the following reasoning.
I have a function that prints data to Excel, and I want to spawn a worker to handle it, Since I can call this function multiple times with different values, I was thinking of using the Pool to queue my worker calls.

Since I require the output in order to save as Excel, I decided to use the Observable feature to listen for the change and trigger the save.

What am I gaining by doing it with an Observable vs without? Is there a reason why I shouldn't?

**Example with Observable:**

```
import { spawn, Pool, Worker } from "threads";

// spawn worker pools
const exportDataTablePool = Pool(() => spawn(new Worker("../../workers/exportDataTable.js")));

window.WorkerPool = {
  exportDataTable: args => exportDataTablePool.queue(exportDataTable => exportDataTable(args).subscribe(result => console.log(result))
}
```

**Example without:**

```
import { spawn, Pool, Worker } from "threads";

// spawn worker pools
const exportDataTablePool = Pool(() => spawn(new Worker("../../workers/exportDataTable.js")));

window.WorkerPool = {
  exportDataTable: args => exportDataTablePool.queue(async exportDataTable => {
    const result = await exportDataTable(args);
    console.log(result);
 }
}
```

And I am calling it like:

```
// can be called multiple times
WorkerPool.exportDataTable({ columns, rows });
```

The example is not 100% exactly like in my code but should give you the general idea of what I am doing.
I am just trying to understand the use case scenarios of when it would be good to use or not use the Observables.

I hope I am being clear, let me know.

Thanks!

**Comment by andywer** [comment]
Hey @simplecommerce. If your worker function is only supposed to return the result, there is no additional value in using an observable.

The reason to use an observable would be to return more than one value per call. For example to return data row by row or just to send progress updates until the result is ready.

Maybe it would make sense to add a short section to the top of the observables page explaining what observables are good for? I thought it's out of scope for threads.js, but maybe it would be worthwhile to make sure people don't get confused.

**Comment by simplecommerce** [comment]
@andywer Thanks for your response, it certainly clarifies it in my mind! I think it wouldn't hurt to just add a small note explaining what you just told me, I personally haven't learned about Observables and how to use them until I ended on your library, so I didn't know lol.

Thanks again!

**Comment by simplecommerce** [comment]
@andywer Last question about pools,
