### ISSUE TITLE
Missing generic type in return type of Transfer<T> (TransferDescriptor<T>)

### ISSUE THREAD

**Issue by N8th8n8el** [andywer/threads.js#347]
I think there is a small type error here:
https://github.com/andywer/threads.js/blob/cf3c1d006438eebdfcbd5b26f801c1fbc7eaa92f/src/transferable.ts#L54

Should probably be:
```ts
export function Transfer<T>(payload: T, transferables: Transferable[]): TransferDescriptor<T>;
```
Or am I missing something?

**Comment by andywer** [comment]
Hey @N8th8n8el!

Sorry for the late reply. Yes, looks like it. I am wondering why TypeScript doesn't mind? …
Will first need to check why tsc didn't complain before.

**Comment by andywer** [comment]
No, look:

https://github.com/andywer/threads.js/blob/cf3c1d006438eebdfcbd5b26f801c1fbc7eaa92f/src/transferable.ts#L3

The type parameter is optional and defaults to `any` 😉
