### ISSUE TITLE
Typescript compile error - , expected in dist/types/master.d.ts

### ISSUE THREAD

**Issue by rathboma** [andywer/threads.js#359]
I'm adding Threads.js to my electron app, [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio). It's built with vue-cli, electron-builder, and webpack.

I added a worker and successfully ran it in dev mode, with the webpack dev server, but when building a package I get the following error:

```
ERROR in /home/rathboma/Projects/beekeeper-studio/studio/node_modules/threads/dist/types/master.d.ts(22,96):
22:96 ',' expected.
    20 |     [methodName: string]: (...args: any) => any;
    21 | };
  > 22 | export declare type ProxyableArgs<Args extends any[]> = Args extends [arg0: infer Arg0, ...rest: infer RestArgs] ? [Arg0 extends Transferable ? Arg0 | TransferDescriptor<Arg0> : Arg0, ...RestArgs] : Args;
       |                                                                                                ^
    23 | export declare type ProxyableFunction<Args extends any[], ReturnType> = Args extends [] ? () => ObservablePromise<StripTransfer<StripAsync<ReturnType>>> : (...args: ProxyableArgs<Args>) => ObservablePromise<StripTransfer<StripAsync<ReturnType>>>;
    24 | export declare type ModuleProxy<Methods extends ModuleMethods> = {
    25 |     [method in keyof Methods]: ProxyableFunction<Parameters<Methods[method]>, ReturnType<Methods[method]>>;
```

It looks like the generated types are incorrect? Or Maybe I did something wrong with my worker?

I've tried writing my test worker in both Typescript and Javascript and it doesn't seem to make a difference.

Please let me know what you think. I think it's 99% likely I just did something wrong, but cannot for the life of me figure out what.

## Code

Here's the exact code I added:
https://github.com/beekeeper-studio/beekeeper-studio/pull/641

**Comment by linonetwo** [comment]
my usage is basically the same as yours, and it is working fine. https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/7c18e0a83be03243477874395060c54618b656a3/src/services/git/index.ts#L44

**Comment by rathboma** [comment]
@linonetwo does it work when you package into an executable? Mines working fine in dev mode.

**Comment by rathboma** [comment]
@andywer Have you seen this error before? I couldn't find it anywhere. Maybe I have a weird typescript setting or something?

**Comment by rathboma** [comment]
So I did some more experimentation. I think this is because I was using typescript 3.9. Looks like the gen'd types only support Typescript 4+

**Comment by andywer** [comment]
Great you two already managed to figure it out. Will merge the TypeScript version note!

**Comment by andywer** [comment]
Btw, I think the TS 4 requirement must have sneaked in very recently. I wasn't aware that it's now required, since as everything was already on TS 4 it didn't impose any problems in CI either.
