### ISSUE TITLE
[QUESTION]: bidirectional messaging

### ISSUE THREAD

**Issue by simplecommerce** [andywer/threads.js#361]
Hi,

Between the main app and the worker thread, is there a way during its execution, to pass data from the worker to the main app and from the main app back to the worker again in a single execution?

I'll try to explain here.

Main app calls Worker and passes it an array of strings.
Worker receives it, loops through it, and when it encounters a specific, it requires additional data, it would pass a message back to the main app to require additional information for the particular string.
Worker waits for the Main app, to send the additional information for this particular string.
Once received, it continues its execution.
When execution is finished, it passes the final result back to the Main app.

Sorry if its unclear.

**Comment by simplecommerce** [comment]
I found a way I can technically achieve this, just not sure if its a good way or not.
I take the instance created by `new Worker()`, and then use `postMessage` in the master and `onmessage` with `postMessage` in my worker to achieve this.

I'll keep playing with it, but I think that would work.

**Comment by andywer** [comment]
Hey @simplecommerce!

The recommended way is to use observables – they are a clean, functional and well-documented alternative to event emitters. See <https://threads.js.org/usage-observables>.

**Comment by simplecommerce** [comment]
@andywer thanks for the reply, yes I thought about using that and I can understand I can subscribe and listen for changes, from the master, but the part I am not sure how to do, is send back data to the current worker when receiving specific messages when I am subscribed to the observer.

I thought I would be able to do the same as the worker and send it an observable also, but this doesn't seem to work.

My current logic is this:

Master executes worker.
- Master listens for any additional requests from the Worker.
- Worker requires additional data, so sends a message back to the Master and awaits the result before continuing its process.
- Master receives request, sends additional data back to the Worker.
- Worker receives additional data, resumes execution.
- Worker returns results to Master and terminates.

I was able to achieve this using the postMessage, onmessage and an Observable (in the worker).

But I am not sure how I could make this work only using an Observable like your example.

**Comment by andywer** [comment]
Ahhh. True, observables in the other direction are currently not possible.

You don't need that, though. To pass data from the main thread to the worker, you can just call worker methods and pass the data as arguments.
