### ISSUE TITLE
BlobWorker missing export from .mjs

### ISSUE THREAD

**Issue by andrewmunro** [andywer/threads.js#378]
I'm trying to import BlobWorker for my project but getting the following error.

![image](https://user-images.githubusercontent.com/1107388/121035896-3a354400-c7a6-11eb-8a6b-3cb2d6b75ec5.png)

Looking at the exports, this file seems to be missing the export...

https://github.com/andywer/threads.js/blob/master/index.mjs

**Comment by andywer** [comment]
Thanks for reporting, @andrewmunro! It's indeed missing…

Just opened a PR. If it's not released by the end of the day, ping me here and I will publish it 🙂

**Comment by PulshaAndrei** [comment]
Hi, @andywer 
as I see it is merged but not published with a new version yet. Is it going to happen soon?
