### ISSUE TITLE
[Question] Upgrading from 0.x, TypeError: threads.spawn(...).on is not a function

### ISSUE THREAD

**Issue by Andargor** [andywer/threads.js#383]
Hello,

I'm upgrading existing code to 1.x from 0.x , and I realize that the new API is breaking. However, I am not sure how to migrate my existing code to the new API without a complete rewrite. I assume I have to use observables or some such? Is there an easy way to support the 0.x syntax?

**Comment by andywer** [comment]
Hey @Andargor.

v0? That hasn't been actively maintained in years. I can barely remember its API anymore. The v0 API wasn't particularly good, though, actually pretty confusing at times and limited, too.

So in short: No, there is no easy way to support that old v0 syntax. That's actually a good thing, trust me. It's some work to port that code, of course, but the old API was basically an incubator for code smells, memory leaks and such.

**Comment by andywer** [comment]
Closing thais issue for now as I don't think there are any actionables.
