### ISSUE TITLE
Thread pool: Job seems not to propagate the `progress` event

### ISSUE THREAD

**Issue by andywer** [andywer/threads.js#39]
The `progress` event might not work with thread pools right now. See [job.js, line 36](https://github.com/andywer/threads.js/blob/4a34c7c6c96f095340c6ad38884f49c59cf6deb3/src/job.js#L36).

## To Do

- [ ] Write test(s)
- [ ] Fix `job` (and maybe `pool`)

**Comment by kukukk** [comment]
Hi,

Any update on this bug? When will it be fixed?

Thanks,
kukukk

**Comment by andywer** [comment]
Hey @kukukk.

Unfortunately not. Low priority right now and I am terribly busy already.

The long-term plan is to release v1.0 with a slightly different API and pretty much a complete rewrite under the hood (see #54), but right now it is still event emitter / callback hell. But if that does not scare you, feel free to open a PR :)

**Comment by andywer** [comment]
v1.0 beta is here with a whole new API. Closing.
