### ISSUE TITLE
How to share memory data to thread?

### ISSUE THREAD

**Issue by fanmingfei** [andywer/threads.js#40]
In nodejs.
Example: 
I have a file storage.js, it has a variable to save some data, I wanna save data in a thread, and get data in another thread.

**Comment by andywer** [comment]
Hey @fanmingfei. Sorry for the delayed response.

Right now there is no real way to share (esp. large) data between threads in node. It uses `child_process.fork()` and thus creates a new process with its own private virtual memory.

One might perhaps be able to build something using http://blog.varunajayasiri.com/node_shm.html 🤔
Not completely sure about that, though.

**Comment by andywer** [comment]
PS: Or something like this: https://github.com/geocar/mmap

But not quite easy to use out-of-the-box either...
