### ISSUE TITLE
expose() called in the master thread.

### ISSUE THREAD

**Issue by PiscoW** [andywer/threads.js#405]
I can use the web app to upgrade my hardware device. If I run it on the main thread, user can not switch tabs while running downloading. So, I am trying to use the library to deal with the downloading process with webusb api. However, when I run my web app, the console shows `expose() called in the master thread`
The expose() is to make either a function or an object callable from the master thread, so my `upgrade.js `file is suppose to run in another thread. And, it does make sense that expose() would be called in the master thread or I misunderstand the way how use the library?

Any suggestion, thanks!

mainjs
```js
import { spawn, Thread, Worker } from "threads"
async download() {
 const worker = await spawn(new Worker("./upgrade"))
 await worker.download()
}
```

upgrade.js
```js
import { expose } from "threads/worker"
expose({
  async download() {
    let device = await navigator.usb.requestDevice()
   //await download from server...
  }
})

```

**Comment by nguyen-vo** [comment]
For anyone who has the same issue in the future when you expose the Worker that file should only expose() the Worker function or module. It should not export any function. When you import any thing from Worker, the expose function will be call in the master thread

example 
```typescript
//Worker.ts
const Components = {
    componentA: () => {
         //do some work 
    }
}

expose(Components)

const otherFunctions= () => {
    //do otherFunctions work
}

export { otherFunctions }
```

```typescript
//Main.ts

import { otherFunctions } from './Worker.ts' // will trigger the expose(Components) function

```
