### ISSUE TITLE
worker with npm module

### ISSUE THREAD

**Issue by pekeler** [andywer/threads.js#44]
I can't figure out how to get a worker that requires/imports an npm lib working in the browser. Works fine on the nodejs side. Is there an example or a guide that shows how to bundle this properly?

**Comment by andywer** [comment]
Unfortunately this isn't easily possible. I once thought about such a feature, but never implemented it...

What you can do:
Bundle your dependency, make it accessible as `window.myDependency` and use that when running in browser. It's ugly, but should at least work.

**Comment by andywer** [comment]
Very hard to find a solution there. No priority at the moment. (Sorry!)
