### ISSUE TITLE
Connecting to database in thread, no result

### ISSUE THREAD

**Issue by crdil** [andywer/threads.js#45]
As the title says I'm trying to spawn a thread which connects to a mssql instance and then returns the result. But for some reason I won't get any result at all. Here is the code

```javascript
const spawn = require('threads').spawn;

const thread = spawn(function(input, done) {
  const sql = require('mssql');
  sql.connect(`mssql://SQLadmin:SQLadmin@${input.ip}/master`)
    .then(() => {
      return sql.query`select * from sys.databases`;
    })
    .then(result => {
      console.log(result);
      done({ string : result });

    }).catch(err => {
      console.log(err);
      done({ string : err });
    });
});

thread
  .send({ ip : '192.168.5.179' })
  .on('message', function(response) {
    console.log(response.string);
    thread.kill();
  })
  .on('error', function(error) {
    console.error('Worker errored:', error);
  })
  .on('exit', function() {
    console.log('Worker has been terminated.');
  });
```

Shouldn't this work?

**Comment by andywer** [comment]
Yeah, that seems like it should work on first glance.

In `thread.on('message')`: Maybe `response.string` is empty?

**Comment by crdil** [comment]
@andywer shouldn't it at least log the results in the promise? ``` console.log(result); ```

**Comment by andywer** [comment]
Hmm, very strange. And the error does not seem to be threads.js-related.

My best guess it that something in `mssql` goes fatally wrong and you never reach the `console.log(result)`

**Comment by andywer** [comment]
Any news on this?

**Comment by andywer** [comment]
Closing, due to inactivity.
