### ISSUE TITLE
any way to set env variables to the forked process?

### ISSUE THREAD

**Issue by grawk** [andywer/threads.js#46]
From what I can tell, no.
https://github.com/andywer/threads.js/blob/6d11ec9269106816fc860eeaeb02a50bddfdf512/src/worker.node/worker.js#L12

Unless there is some way to pass in `options`... Cursory look, I don't see that it's possible.

I've been developing a feature around this module, but may need to have this ability in order to move forward. I'd consider putting in a PR but wanted to get a read on whether you think this is a feature you'd like to have.

Thanks!

**Comment by andywer** [comment]
Hey @grawk.

Documentation is not particularly good I guess, but you should able by passing `options` to the worker. Set `options.env` like in https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

**Comment by grawk** [comment]
So is there an existing API in this module where I can pass this (`options.env`)? I got a call stack from just before `process.fork` here:
```
Trace: Here I am!
    at new Worker (/Users/..
/node_modules/threads/lib/worker.node/worker.js:32:15)
    at spawn (/Users/..
/node_modules/threads/lib/index.js:34:10)
    at Function.Pool.spawn (/Users/..
/node_modules/threads/lib/pool.js:153:30)
    at new Pool (/Users/..
/node_modules/threads/lib/pool.js:35:26)
    at Object.<anonymous> (/Users/..
/threader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

From looking at the code and doing some trial/error it doesn't appear that there is an option for me to pass in an argument through any of the existing threads.js APIs to affect this.

**Comment by grawk** [comment]
After further analysis, I can pass the options object to the exported `spawn` method. But if I'm using the `Pool` feature, I cannot pass the options object..

**Comment by grawk** [comment]
I think for my use case I can proceed for now using threads directly.. But I think this could be a nice enhancement to the module, to be able to pass in options to each spawned process in a `Pool`.

**Comment by andywer** [comment]
Ahh, yeah. The `Pool` does currently not accept any options... :-/

Being able to pass options to `Pool` as a 2nd constructor param might be good.

**Comment by andywer** [comment]
Closing this for now. Created a new issue for the options parameter: #47
