### ISSUE TITLE
Node: no handle for 'unhandledRejection'

### ISSUE THREAD

**Issue by mijay** [andywer/threads.js#49]
While `worker.node/slave.js` subscribes and nicely handles `'uncaughtException'` event, similar `'unhandledRejection'` is not handled there. And hence, promise-based workloads don't have the same "last resort" error catching as callback-based.

**Comment by andywer** [comment]
Hey @mijay.

This is a good point. Wanna open a PR?

**Comment by mijay** [comment]
Done
