### ISSUE TITLE
Pool size

### ISSUE THREAD

**Issue by KrishnaPG** [andywer/threads.js#6]
This is good work. Thanks for sharing.

Wondering how to specify the pool size (no. of threads to be created), and its scheduling characteristics?

Also, how are the jobs scheduled in the pool? Do the threads `pull` the jobs from a waiting-queue or are the jobs `queued/pushed` onto the threads?

In the later-case, would it be possible to specify thread-scheduling criteria (such as 'roundrobin', 'least-used' etc...). ?

**Comment by andywer** [comment]
Hey Krishna! Thank you.

Have a look at the updated README on the develop branch: https://github.com/andywer/threads.js/tree/develop#thread-pool

You can pass the pool size to the constructor. It defaults to the number of CPU cores.

Scheduling works as follows:
You pass a new job to the pool.
1. There is an idle worker: The idle worker runs the job.
2. All workers are busy: The job is queued in a FIFO queue. Everytime a worker has finished its job, it will take the oldest job from the queue, remove it from the queue and run it.

So one worker only runs one job at a time.
Might need to improve documentation... ;)

Does that answer your question?

**Comment by KrishnaPG** [comment]
Yes. Thank you for the quick response. It is helpful.
