### ISSUE TITLE
With webpack build, `__dirname` in `lib/worker.node/worker.js` points to "/"

### ISSUE THREAD

**Issue by wgerven** [andywer/threads.js#61]
Hi, 

I ran into the following issue: I am using `threads` in a typescript project of mine. I use webpack to transpile. I successfully build my project, but when I run it, I get the error `Error: Cannot find module '/slave.js'`.

I have been digging a bit, and the error originates from `node_modules/threads/lib/worker.node/worker.js`, line 37: 

    _this.slave = _child_process2.default.fork(_path2.default.join(__dirname, 'slave.js'), [], options);

Problem statement: 

- When I use webpack to build my project, `__dirname` points to "/"
- **however**, when I simply execute with `ts-node`, `__dirname` does contain the correct path, and the thread successfully runs the referenced script.

Could somebody perhaps assist me in solving this issue (other than hacking in worker.js :) )

Thanks,
Willem

**edit:** this concerns code which is to be run on the server.

**Comment by andywer** [comment]
Hey @wgerven!

Thx for reporting the issue. Can you please try if the following patch works?

Add this line to your `node_modules/threads/package.json`:
```diff
  "browser": {
+   "./lib/worker.js": "./lib/worker.browser/worker.js",
    "child_process": false,
    "os": false,
    "path": false
  }
```

**Comment by wgerven** [comment]
Hi @andywer ,
Thanks for getting back to me this fast. Unfortunately your proposed patch did not have any effect (reported error is the same).

**Comment by wgerven** [comment]
Just to emphasize, as I didn't mention it explicitly in my original post: I am transpiling for *node*.

**Comment by andywer** [comment]
Ahh. Well, that's a game changer... 😅

The issue seems to be rather webpack-related. This should fix it: <https://github.com/webpack/webpack/issues/1599#issuecomment-186841345>

**Comment by wgerven** [comment]
Yes, that indeed seems to point to a solution. (However, it doesn't work out of the box... `__dirname` now points to the folder of the build, so it looks for slave.js in the build directory. :S )

**Comment by andywer** [comment]
TBH I never thought about using it with webpack on the server-side. A quick fix might be adding a `CopyPlugin` to cooy the slave.js to the build directory.

Maybe we can patch the library to use `require.resolve('./slave')` or similar. Feel free to monkeypatch the worker.js to see if it works 😉

**Comment by andywer** [comment]
Any updates on this?

**Comment by andywer** [comment]
Closing until further complains arrive 😉

**Comment by gorilla-devs** [comment]
I am getting the same error. I am running nodejs with electron -> https://github.com/chentsulin/electron-react-boilerplate. Any idea on how to solve that?
