### ISSUE TITLE
[Question] Worker and domains

### ISSUE THREAD

**Issue by cajus** [andywer/threads.js#62]
Hi. This is more a question than a real bug report:

I'd like to use the _IndexedDb_ from within the worker script (I'm using the pool on the non-worker side) and share that _IndexedDb_ with the main application.  Sadly that's not possible, because the worker gets injected by a Blob-URL and - as a result - runs in a different security domain. There's no shareable _IndexedDb_ possible with that setup - except when commenting some lines to use the IE fallback.

Any idea how that can be achieved?

**Comment by andywer** [comment]
Hey @cajus. I suppose we are talking about usage in browser only.

Instead of passing a function to `spawn()` you could pass the URL of a separate script file to run in the worker. If this script resides in the same origin, the IndexedDb should be the same.

Plan B: Depending on what you need to do it might be an option to access the IndexedDb only in the worker or only in the host script and rely on message passing between them only if the other one needs to access the IndexedDb.

**Comment by cajus** [comment]
@andywer thanks for the quick reply!

That's the part that is configuring the pool:

```
    config.set({
      basepath: {
        browser: '/resource/js'
      }
    })

    this._pool = new Pool()
    this._pool
      .on('done', this._onMessage.bind(this))
      .on('error', this._onError.bind(this))
      .run('index.js') 
```

And `index.js` is a script. But it's using the Blob object. Maybe that's the wrong way I'm using it?

Plan B is not an option, because I would have to copy over tons of data from the model to the ordinary browser space. Which will in turn mean that I've that data doubled and need to maintain changes.

**Comment by andywer** [comment]
By "it's using the Blob object" you mean it's encoding the source to a data URI to feed the web worker constructor with?

That shouldn't be the case... You code snippet looks fine on first glance, though.

Your issue descriptions seems to indicate that [thread.runMethod()](https://github.com/andywer/threads.js/blob/master/src/worker.browser/worker.js#L82) is run, while [thread.runScripts()](https://github.com/andywer/threads.js/blob/master/src/worker.browser/worker.js#L84) should be run instead. Maybe you can debug if this is the case?

**Comment by andywer** [comment]
@cajus This has been fixed now, right? Feel free to re-open if not.
