### ISSUE TITLE
Capture workers' stdout

### ISSUE THREAD

**Issue by Bamieh** [andywer/threads.js#65]
Hello,
Is there a way to capture the `stdout` of a single worker in the thread pool?

maybe by passing a config function like such:

```
function(err, stdout, stderr) { 
    console.log(stdout); 
}
```

My node terminal logging is all mixed together by the different threads, is there a way to fix that?

Cheers!

**Comment by andywer** [comment]
Hey @Bamieh!

Interesting point. Currently there is no such thing available and most people will probably not log in the threads, but yeah... The thing is that then you'd have to highlight which line of output comes from which thread, pretty much like `docker-compose logs`.

**Comment by andywer** [comment]
Looks like a "won't fix for now". If you have a proposal how to add such a feature with reasonable effort, feel free to open a PR or re-open the issue 😉

**Comment by Bamieh** [comment]
@andywer I ended up using `intercept-stdout` inside the worker file, sometihng as such:

```
const intercept = require("intercept-stdout");
const worker = function(done) {
  const unhook_intercept = intercept(function(text) {
    stdoutCapture.stdout.push(text);
    return ""
  });
  ...
  unhook_intercept();
  done()
} 
```
