### ISSUE TITLE
SecurityError

### ISSUE THREAD

**Issue by xEviL** [andywer/threads.js#7]
Tried to used `threads.js` and maybe I'm doing something wrong, but:

https://jsfiddle.net/aorx7stg/

in javascript console:
```
Uncaught SecurityError: Failed to construct 'Worker': Script at 'data:text/javascript;charset=utf-8,/*eslint-env%20worker*/%0A/*global%20imp…ndlerDone,%20handlerProgress.bind(this));%0A%20%20%7D%0A%7D.bind(self);%0A' cannot be accessed from origin 'https://fiddle.jshell.net'.
```

**Comment by andywer** [comment]
Hey there! I think this is a cross-domain issue with jsfiddle.net and its "result" view iframe being served from another domain than the main page. (Compare http://stackoverflow.com/questions/23953543/cross-domain-web-workers)

It should work when used by the main page (not in an iframe). But I will have a look if there is a work-around to make it work with jsfiddle...

**Comment by ddoherty** [comment]
I'm getting that same thing in my web app hosted on MAMP on Mac (not on jsfiddle).
Should be no cross-domain issue (it's served by http).
Is something being pulled in via a file reference?

Choking on:
````
/*eslint-env worker*/
/*global importScripts*/
/*eslint-disable no-console*/
self.module = {
  exports : function() {
    if (console) { console.error('No thread logic initialized.'); }
  }
};

function handlerDone() {
  var args = Array.prototype.slice.call(arguments, 0);
  this.postMessage({ response : args });
}

function handlerProgress(progress)...s.module.exports;
    if (typeof handler !== 'function') {
      throw new Error('Cannot run thread logic. No handler has been exported.');
    }

    var preparedHandlerDone = handlerDone.bind(this);
    preparedHandlerDone.transfer = handlerDoneTransfer.bind(this);

    handler.call(this, event.data.param, preparedHandlerDone, handlerProgress.bind(this));
  }
}.bind(self);
````

**Comment by andywer** [comment]
@ddoherty Are you accessing it via `http://localhost`? This is a browser security feature that prevents web workers from working when accessed via `localhost` or `file://`. It's pretty nasty. I should probably add a hint to the README. But it's not an issue with the library, but with the web worker specification.

**Comment by ddoherty** [comment]
Running on MMAMP on Mac with the following URL: http://192.168.1.112:8081/home.
Tried using the Python basic webserver as well as webpack's server.  No go.

**Comment by tchakabam** [comment]
@ddoherty @andywer 

I had the same issue and could fix it by using this Polyfill: https://github.com/Rob--W/chrome-api/blob/master/patch-worker/patch-worker.js

just run the above before whatever you do, works like a charm for me :)

**Comment by andywer** [comment]
@ddoherty @tchakabam There might also be a very simple fix: Don't use threads.js hosted on a CDN, but having it served from your machine.

Only problem is that the jsfiddle snippet still won't work.

**Comment by andywer** [comment]
@ddoherty @tchakabam Ahhh, now I know why nobody answered. My post got lost...
The bug should be fixed in this branch: https://github.com/andywer/threads.js/tree/security-error-fix

Will merge it into the master branch.

**Comment by andywer** [comment]
PS: You may use `<script src="https://cdn.rawgit.com/andywer/threads.js/security-error-fix/dist/threads.browser.min.js"></script>` to test it.

**Comment by tchakabam** [comment]
oh cool thanks will definitely check that out!

**Comment by maysale01** [comment]
+1 @andywer Fix is working for me.

**Comment by devongovett** [comment]
Any chance this will be merged and released soon?

**Comment by andywer** [comment]
Hi! Thanks for the reminder. Yes, I'm going to merge and release this evening :)

**Comment by andywer** [comment]
Merged and released 0.5.4. Does not yet include the commit for #12, since I am not yet sure what the problem is. Sorry for the inconvenience, but I am terribly busy these days...

**Comment by maysale01** [comment]
Thanks for your hard work. I'll try to find time to dive further into that
issue. Perhaps we should move it to a new issue and fully define it. Is the
expected behavior for all available threads in a pool to receive the
message or just 1? It seems that the resolved value of a Promise returned
by .promise() doesn't match the original message when sent to a pool. Let
me see if I can reproduce and make a new issue. In the meantime, the fix in
#12 does fix the issue that was originally referenced.

**Comment by andywer** [comment]
@maysale01 Thanks for your reply. I wrote a functional test for #12 and there I can also see this weird behavior. Figured out that everything in threads.js should be promise-based, top to bottom. That's also a great factor for stability in error scenarios.

Currently everything is callback-based and the promise API on top is just a gimmick. This will probably always cause trouble.

I also have some other less severe things I would like to change. **So maybe it has come the time for threads 1.0** with *very slightly changed API* built on a *promise-based approach*. Just got to find time for this... (which is indeed a problem)

**Comment by maysale01** [comment]
@andywer I'm not so sure moving away from EventEmitter is going to be a painless endeavor. However, I do think the API needs to be revisited as run/send are very confusing (run just sets parameters, send proxies from Pool -> Job -> Thread). 
    
I'm inclined to think that this particular issue is because of the passing of `thread` by reference in `Pool.dequeue` to the `handleJobSuccess` and `handleJobError` event callbacks. Would you mind sharing your functional test so we can use the same benchmark?

**Comment by andywer** [comment]
Yeah, the changes would be a whole lot of work, but in retrospect the idea of having a event-based library and putting a promise-based API on top of it as a gimmick seems inappropriate. The other way round would be way more preferrable, I think.

I put the functional test here: https://gist.github.com/andywer/8486bc916ff22c1f6d7d
