### ISSUE TITLE
'finished' not emitting

### ISSUE THREAD

**Issue by jamesAtcodeninja** [andywer/threads.js#71]
Running this code prints `done` 10 times, but `finished` does run.

```js
  for (let i = 0; i <= 10; i++) {
        pool
          .run(function(i, done) {
            done(i)
          })
          .send(i)
          .on('done', function (i) {
            console.log('done', i)
          })
          .on('error', function (e) {
            console.error(e)
          })
          .on('finished', function () {
            console.log('finished')
          })
      }
```

**Comment by andywer** [comment]
Hey @jamesAtcodeninja, thanks for reporting!

Really seems to be an issue: Wrote a [webpackbin snippet](https://www.webpackbin.com/bins/-L1rnFurcDCrImZhiKdI) to reproduce the issue.

**Comment by andywer** [comment]
Found it! It's not exactly an issue with the library, but rather a usability issue with event emitters.

```js
.on('finished', function () { /*...*/ })
```

is a `job.on('finished', function () { /*...*/ })`. But it must be:

```js
pool.on('finished', function () { /*...*/ })
```

Not sure how to make sure that you don't subscribe to events that don't exist, though. Any ideas?
I already thought about emitting `finished` on the jobs as well, but quite frankly, that doesn't make too much sense.

**Comment by jamesAtcodeninja** [comment]
How about using methods instead? 
Something like `pool.onFinished(function () { .... })`

**Comment by andywer** [comment]
Might be a solution, but I am actually hesitant to introduce a breaking API change for that, since in the long term I‘d like to migrate away from event emitters altogether (see #54).
