### ISSUE TITLE
NodeJS : threads do not/cannot contain global

### ISSUE THREAD

**Issue by rob2d** [andywer/threads.js#74]
Hi, I have noticed there is an issue when you try to access or even define `global` on any NodeJS thread. Is there some way that this sort of functionality can be added to new spawned processes? I realize globals aren't typically best practice, have several scripts which rely on a few variables that I would like to be able to migrate to/from the code in relation to directories/file structure.

**Comment by andywer** [comment]
Hey @rob2d.

Yeah, it pretty much boils down to:
- globals are bad practice and
- it cannot easily be done across threads

Sorry for the bad news 😉
