### ISSUE TITLE
Does not work in node on Windows (?)

### ISSUE THREAD

**Issue by FahimSiddiqui** [andywer/threads.js#75]
As the document says, "*Threads Uses web workers when run in browsers and child processes when run by node.js*", I am able to write a piece of code which runs on the browser(using web worker model) but same code does not work on Node(Server side - using child process).

Note: I could not find enough support for above library in Typescript, I am using the js package in typescript code.

```ts
import { spawn } from "threads/lib";
const thread = spawn((value: any,  callback: (_: any) => any ) => { console.log("X: " + value.x + " Y:" + value.y );  callback({ result : value.x + value.y } ); });
thread.on("message", (value: any) => {console.log("Addition: " + value.result); } );
thread.on("error", (message: any) => { console.log("Error: " + message); });
thread.send({x : 1, y : 5});
```

Above written code works fine while running on the browser(returns 6). But it neither returns anything nor throws any error on the Node.

I have a complete node js setup and I have been using it since a bit long[On windows 10].

Could someone please take a look as why its not working for Node or if I have missed any step in between, or let me know if more details are needed.

Thank you in advance.

**Comment by andywer** [comment]
Hey @FahimSiddiqui.

I tried your code locally on my machine (Mac OS X 10.11) and it worked fine. Maybe it's a Windows issue 🤔

I fear I can't help you here, since I have no Windows machine around...
Here is what I did:

```
andy@Andys-MacBook:/tmp/threads-75$ echo '{}' > package.json
andy@Andys-MacBook:/tmp/threads-75$ npm i threads
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN threads-75 No description
npm WARN threads-75 No repository field.
npm WARN threads-75 No license field.

+ threads@0.10.1
added 3 packages from 3 contributors in 7.307s
andy@Andys-MacBook:/tmp/threads-75$ vi index.ts
andy@Andys-MacBook:/tmp/threads-75$ cat index.ts 
import { spawn } from "threads/lib";
const thread = spawn((value: any,  callback: (_: any) => any ) => { console.log("X: " + value.x + " Y:" + value.y );  callback({ result : value.x + value.y } ); });
thread.on("message", (value: any) => {console.log("Addition: " + value.result); } );
thread.on("error", (message: any) => { console.log("Error: " + message); });
thread.send({x : 1, y : 5});

andy@Andys-MacBook:/tmp/threads-75$ npm i typescript ts-node
npm WARN threads-75 No description
npm WARN threads-75 No repository field.
npm WARN threads-75 No license field.

+ typescript@2.7.2
+ ts-node@5.0.1
added 18 packages from 44 contributors in 18.528s
andy@Andys-MacBook:/tmp/threads-75$ node -r ts-node/register index.ts 
X: 1 Y:5
Addition: 6
^C
andy@Andys-MacBook:/tmp/threads-75$ 
```

**Comment by andywer** [comment]
**Request for comments:**
Maybe someone else used *threads* on Windows before?

**Comment by LightningBladeXYZ** [comment]
I am using threads on windows, but only very basically (and currently only in testing) and it works fine for me rn. I can also run the above just fine: 
(Please excuse the mess in the console)
![2018-05-06 5](https://user-images.githubusercontent.com/27926588/39670741-4987339a-5103-11e8-9eec-7ec62ae549f6.png)

**Comment by andywer** [comment]
Thanks, @LightningBladeXYZ!

Now it seems likely that it's an issue with your local setup, @FahimSiddiqui. Really hard to tell from here, though...

I am gonna close this issue for now under the assumption that it's some kind of personal, local problem. If anyone else encounters the issue, feel free to re-open 😉

**Comment by dcerisano** [comment]
Threads persistence is broken in Windows 10. One-shot non-persistent threads work fine. 

Windows 10 throws the following error when interacting with persistent threads (threads that do not exit after done).  Windows 10 thread pools  throw same error after the number calls exceeds the pool size. 

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:599:16)
    at Worker.send (C:\..\node_modules\threads\lib\worker.node\worker.js:108:16)
```
