### ISSUE TITLE
Webpack cannot resolve module 'child_process'

### ISSUE THREAD

**Issue by ddoherty** [andywer/threads.js#8]
Trying out threads.js

Ran into a problem building my app for distribution w webpack:

```
ERROR in ./~/threads/lib/worker.node/worker.js
Module not found: Error: Cannot resolve module 'child_process' in /theApp/node_modules/threads/lib/worker.node
 @ ./~/threads/lib/worker.node/worker.js 11:21-45
```

Similar to (?):
https://github.com/webpack/webpack/issues/744

which suggests adding:

```browser: { fs: false, child_process: false }``` to ```package.json```

Thoughts?  Thanks!

**Comment by andywer** [comment]
Can you please try adding the following to your webpack config?

```javascript
{
  // ...
  alias: {
    threads: "node_modules/threads/dist/threads.browser.js"
  }
  // ...
}
```

So you will be using the browserified bundle and webpack does not try to bundle the node.js files, too.

**Comment by ddoherty** [comment]
Tried it.  Same error as above.  :(

**Comment by ddoherty** [comment]
btw,  I've since learned that I'm probably not going to be able to use threads.js in my app. Am running C++ code converted by emscripten and it looks like I'll have to be running within the emscripten environment using its Web Workers API.

I can close my issues if you want or I can test a few more things for you, if you're interested.

Thanks for the support.

**Comment by andywer** [comment]
Hmm, too bad. But I would be glad if you can test it a little more :)

I will have a look at the issues when I find some time for it.
Thanks for your testing!

**Comment by daiheitan** [comment]
Maybe you could try this:

https://github.com/webpack/webpack/issues/744

**Comment by andywer** [comment]
Hey daiheitan. Thanks a bunch!

@ddoherty Could you try again with threads' develop branch?
