### ISSUE TITLE
Communication with all active workers in a pool

### ISSUE THREAD

**Issue by Neoflash1979** [andywer/threads.js#82]
So if I understand correctly, calling the `send` method on a pool actually prepares a new job with the parameters passed, which will be picked up by the next available idle worker. But what if I want to send a message to all active workers in a pool, what is the best way of doing that.

Use case pseudo-code:

*main*
```
pool.run('worker')

// If I understand correctly each call to `send` creates a job 
// which will be picked up by an idle worker
pool.send(someData) 
pool.send(someDate)
pool.send(someData)
pool.send(someData)

let aggregate

pool.on('message', function(resultOfSimulation) {
  aggregate += resultOfSimulation
}

if (someCondition) {
pool.tellAllActiveWorkers("we're done, you can stop now and send me your result")
}
```

*worker*
```
function(input, done) {
  let resultOfSimulation
  while(someCondition) {
    if (gotMessageThatICouldStop) {
      break
    }
    // run some long CPU hogging simulation
  }  
 done(resultOfSimulation)
}
```

**Comment by andywer** [comment]
Might be possible in v1.0 with `spawnStateful`. Feel free to checkout the draft (#88) and share your feedback if you are still looking for a solution 😉

**Comment by andywer** [comment]
Closing, since there is little that can be done about it now.
