### ISSUE TITLE
API for Version 1.0

### ISSUE THREAD

**Issue by andywer** [andywer/threads.js#88]
## Draft of new API

This new API is supposed to fix pretty much everything listed in #54, make the library more convenient to use and less error-prone. The new code should also be easier to maintain.

The library will probably be rewritten completely in TypeScript. Instead of event emitters there shall only be promises and observables, since they are basically side-effect free and way easier to debug.

**Request for comments: Is that API easily understandable? Are you comfortable using observables instead of event emitters?**

### Basic

```js
import { spawn } from 'threads'

const multiply = spawn(async (a, b) => {
  return a * b
})

multiply(2, 3).then(result => {
  console.log(`2 x 3 = ${result}`)
  multiply.kill()  // Worker would otherwise stay alive
})
```

### Streaming from Worker with Progress

The worker code shall ship with a tiny Observable implementation (accessible as `this.stream()`), extended by `progress` updates.

On the main thread's side, the `threads` lib will return a zen-observable instance that is extended by a `progress` method, returning another observable the user can use to subscribe to the progress (will never yield an error).

```js
import { spawn } from 'threads'

const create20Numbers = spawn(function () {  // <- No arrow function (!)
  return this.stream(({ next, complete, error, progress }) => {  // <- tiny Observable implementation with `progress`
    let yieldedNumbers = 0

    for (let index = 0; index < 20; index++) {
      next(Math.random())
      progress(this.progress(index / 20))
      yieldedNumbers++
    }

    if (yieldedNumbers !== 20) {
      return error(new Error(`Expected to yield twenty numbers, but only seemed to yield ${yieldedNumbers}`))
    }
    complete()
  })
})

const observable = create20Numbers()

observable.subscribe({
  next (value) {
    console.log(`New value:`, value)
  },
  complete () {
    create20Numbers.kill()  // only using this worker for a single job
  },
  error (error) {
    console.error(`Error in worker:`, error)
  }
})

observable.progress().subscribe({
  next (progress) {
    console.log(`Progress: ${Math.round(progress * 100)}%`)
  }
})
```

Or simply:

```js
import { spawn } from 'threads'

const create20Numbers = spawn(/* ... */)

create20Numbers().forEach(value => {
  // the worker function will return a zen-observable which comes with `forEach` & friends
  console.log(`New value:`, value)
}).then(() => {
  create20Numbers.kill()
}).catch(error => {
  console.error(`Error in worker:`, error)
})
```

### Streaming to Stateful Worker

```js
import { spawnStateful } from 'threads'

const minmax = spawnStateful(function (calls) {
  let min, max

  return (number) => {
    if (min === undefined || number < min) {
      min = number
    }
    if (max === undefined || number > max) {
      max = number
    }
    return { min, max }
  }
})

minmax(2)
minmax(3)
minmax(4)
minmax(1)
minmax(5).then(result => console.log(`Min: ${result.min}, Max: ${result.max}`)
minmax.kill()
```

### Thread Pool

```js
import { createPool, createJob } from 'threads'

const pool = createPool()
// Alternatively: createPool(<number of threads to spawn>)

const add = (numbers) => {
  // This arrow function is not explicitly `async`, when run in a worker it will return a Promise, though
  return numbers.reduce((sum, number) => sum + number, 0)
}

const promiseOrObservable = pool.schedule(createJob('/path/to/worker', { do: 'something' }))
const additionPromise = pool.schedule(createJob(add, [1, 2, 3]))

pool.events().forEach(event => {
  console.log(`Pool: ${event.type}:`, event.payload)
})

pool.idle().then(() => pool.kill())
```

You can even abort jobs:

```js
const job = createJob(add, [1, 2, 3])
const jobPromise = pool.schedule(job)

job.abort()  // jobPromise will be rejected with an abortion error
```

### Transferables

Use the exported `transferables()` helper, wrap your transferables in it and pass them as an additional (last) parameter on worker invocation.

```js
import { spawn, transferables } from 'threads'
import readFile from './read-file'

const someBuffer = readFile()

const hashBuffer = spawn(async (buffer, options) => {
  // ...
  return this.transferable(buffer)
})

hashBuffer(someBuffer, { fast: true }, transferables([ someBuffer ]))
```

**Comment by gtdminh** [comment]
+1 for promise based approach. thank you.
can you share a roadmap when it is ready for production usage ?

**Comment by andywer** [comment]
@gtdminh This is where it gets tricky... I'm afraid there is no ETA on this yet. Am already plenty busy, plus have [shutter.sh](https://shutter.sh/) which is very early stage and a new project which will see the light of day very soon.

Let's see how those things turn out and how much attention this draft receives 😉

**Comment by andywer** [comment]
Question to all:
Do you feel that this new API is still intuitive enough or does it feel more complex than the current API?

Would also be great to get some feedback from users that rely on advanced functionality like streaming data, pool job cancellation, transferable array buffers, ... 😉

**Comment by ItsEcholot** [comment]
I just started looking into this library but the proposed new api using promises & observables seems way better suited for workers then the event based approach used right now.

**Comment by aaronbeall** [comment]
> Do you feel that this new API is still intuitive enough or does it feel more complex than the current API?

Yes! I think it's a big improvement. I have also just started looking for a threading library for my JS project, so I don't have a lot of real-world experience yet, but the proposed API would be a lot easier for me to adopt. 

> The library will probably be rewritten completely in TypeScript

Awesome! Is there any work-in-progress branch yet? I may be able to help.

**Comment by andywer** [comment]
@aaronbeall Not yet, unfortunately. I would appreciate some help, though, once development gets started.

There is one more thing blocking the whole v1.0 dev right now:
We first need to come up with a proper minimal hot observable implementation, I think... Like zen-observable, but with hot observables (so one observable with n subscriptions equals the observer code being run once, not n times).

**Comment by andywer** [comment]
Progress, after all!

In the last days I started to re-implement `threads` for v1.0. The API is close-ish to what was outlined here, but refined further. It is not complete yet, but what has been implemented does work.

Please go and have a look at it if you can: See #100 (contains a link to the `v1` branch) and leave further feedback there 🙂
