### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by zimond** [andywer/threads.js#9]
After reading the doc for 2 times I still do not know the clear API of `Worker`, so if I want to spawn a thread to run `function a()` and then `function b()`, is this the correct code?

``` js
spawn(function a() {})
.send({/*data for fn a*/)
.run(function b(){})
.send(/* data for fn b*/)
.promise()
.then(function(finalResult) { /* ... */})
```

**Comment by daiheitan** [comment]
Or, `.run` is only available for `Thread` ?

**Comment by andywer** [comment]
I'm terribly sorry I never replied to this issue! And I agree, the old API was super confusing.

Version 1.0 is a fresh restart, so let's make it right this time (see #100).
