### ISSUE TITLE
How to deal with common dependencies between workers.

### ISSUE THREAD

**Issue by zenaway** [andywer/threads.js#90]
Your threads are very useful and well used. However, when you create a worker, it is necessary to process require for each module because of dependency. I have tried various methods and let me know if there is a way to require dependencies in common

like this
```
const axios = require('axios');

exports.workerA = () => {
    axios.get("https://get.com/path").then((resp)=>{
        console.log(resp);
    }).catch((err)=>{
        console.log(err);
    })
}
exports.workerB = () => {
    axios.post("https://post.com/path").then((resp)=>{
        console.log(resp);
    }).catch((err)=>{
        console.log(err);
    })
}
```

But now is the code that works normally

```
exports.workerA = () => {
    const axios = require('axios');
    axios.get("https://get.com/path").then((resp)=>{
        console.log(resp);
    }).catch((err)=>{
        console.log(err);
    })
}
exports.workerB = () => {
    const axios = require('axios');
    axios.post("https://post.com/path").then((resp)=>{
        console.log(resp);
    }).catch((err)=>{
        console.log(err);
    })
}
```

**Comment by andywer** [comment]
I am not sure what you mean by "But now is the code that works normally"... Also: What is your frontend setup?

If the second code snippet does not work in node and in the browser for you, please add the error you get.

**Comment by zenaway** [comment]
My front end configuration works in the node environment because
it works in the main process of electron 2.0.3.

I was wondering if there is a way to handle the dependencies that are needed in common, like the first code.

**Comment by andywer** [comment]
I am not sure if I got your question right, but I will try to answer anyway:

So if you are running an electron app and you are just wondering about how to use external packages in your worker code, then just stick to the second approach mentioned above. The first code snippet will not work, since the functions will be serialized and send to the worker, so they cannot reference outside variables.

I hope that answers your question. If not, feel free to re-open 😉

**Comment by zenaway** [comment]
I am sorry to confuse you because of your lack of English ability.
Unfortunately, I will keep it in the first way.
