### ISSUE TITLE
timeout for worker

### ISSUE THREAD

**Issue by gtdminh** [andywer/threads.js#91]
```js
let job = spawn(fn).send({args});
job.setTimeout(10000);//100s timeout
//or 
//job.setTimeout(10000, timeoutHandler);
function timeoutHandler(job){
   job.abort();
}
```

what do you think about this ?
currently i need to use setTimeout to do the same thing for workers.

**Comment by andywer** [comment]
Yeah, I see your point. I wouldn‘t add another method to the worker, though. The node.js worker accepts `options` as a 3rd parameter passed to `spawn()` already.

We could add `timeout` to those `options` and make the browser worker interpret those options as well. I would vote for triggering the existing `error` event on timeout.

What do you think?

**Comment by gtdminh** [comment]
i agree. 
in your document, when abort() is called , i thought you already triggered reject on promise. am i correct ?

**Comment by gtdminh** [comment]
i am willing to do PR for this as well.

**Comment by andywer** [comment]
Ahh, sorry, I think we were both wrong... `job.abort()` is only a pool job thing, not a worker feature. Your code snippet above is wrong w.r.t. not scheduling a pool job, but just spawning a worker.

I don‘t see an elegant way to implement the timeout functionality on pool jobs before #88.

Should be able to do it on worker level, but then the timeout handler would kill the worker instead or so.

**Comment by gtdminh** [comment]
i am using pooled jobs. so better wait for #88 right ?

**Comment by andywer** [comment]
Basically yes, but I am really not able to give an ETA when that will be done... 😕

**Comment by andywer** [comment]
Closing as *won't fix* for now, sorry. Need to wait for the new API first.
