### ISSUE TITLE
Initialize all threads in pool

### ISSUE THREAD

**Issue by nickman** [andywer/threads.js#93]
Is there a way to pre-load worker code into each 'thread' in the pool ? i.e. if I create a pool with 4 threads, I want each thread to run some code so when I start submitting tasks, the code will be loaded already.

(Also need to register a shutdown handler, but I think the above question answers that.)

Thanks !

**Comment by nickman** [comment]
This is in the browser. (I am passing off WASM operations to workers)

**Comment by andywer** [comment]
Hey @nickman!
You should be able to call `pool.run(/* ... */)` once and then call `pool.send(/* ... */)` any number of times.

**Comment by andywer** [comment]
The current API isn‘t particularly explicit, I have to admit. #88 might make things better in the future.

**Comment by andywer** [comment]
Closing the issue. Feel free to re-open if my suggestion didn‘t work.
