### ISSUE TITLE
slave.js eats 100% of cpu

### ISSUE THREAD

**Issue by armenmargaryan** [andywer/threads.js#94]
Hi,

i'm using threads: 0.12.0
node: v10.10.0
and pm2 version is 2.10.1

and from time to time threads/lib/worker.node/slave.js starts to eat 100% of cpu of all cores
![untitled](https://user-images.githubusercontent.com/6891642/46515396-a1bbc880-c874-11e8-8ccb-cc6d8e1cecd7.png)

here is my packages.json

     {
		"name": "******",
		"version": "0.0.0",
		"dependencies": {
				"express": "4.16.3",
				"socket.io": "1.7.3",
				"mysql": "2.16.0",
				"cache-storage": "2.0.1",
				"dateformat": "3.0.3",
				"threads": "0.12.0",
				"deep-extend": "0.6.0",
				"fs-extra": "7.0.0",
				"node-datetime": "2.1.2"
		}
     }

in code i used thread as something like cron

    const thread = threadsSpawn(function(input, done) {
			
          const fse = require('fs-extra');
			
          const SN_INTERVAL = setInterval(function(){
				if( fse.pathExistsSync(input.var_path+'/new_notification') ){
					clearInterval(SN_INTERVAL);
					done();
				}
          }, 15000)// 5s
    })
    .on('message', function(response) {
              .....do some logick
             thread.send({'var_path': VAR_PATH});
    })
    .send({'var_path': VAR_PATH});

**i have recently updated from "threads": "0.7.*", to 0.12.0 and before i did not experienced such issue code of cron was same**

**Comment by andywer** [comment]
Hey @armenmargaryan, thanks for the detailed issue description! 👍

Sorry for the delayed response, but I am very busy at the moment. The information you provided is really helpful, esp. the version 0.7 -> 0.12 upgrade. I hope I will find some time to look into it next week.

**Comment by armenmargaryan** [comment]
Hi ok, yes pls it making us a lot problems. 
Currently i downgraded it back.

**Comment by andywer** [comment]
It‘s tricky without having some sample code to reproduce the issue, but I will try anyway:

Can you upgrade back to v0.12 and add a line at the beginning of the `messageHandlerError` function in `slave.js`, logging the error that is handled?

It's most likely the error handling code, but we need to know what the error is.

**Comment by armenmargaryan** [comment]
ok will try it on our development server

**Comment by armenmargaryan** [comment]
Hi, i have added logs in place as you mentioned, and 100% cpu happened again but i did not get any log with error message ...

**Comment by andywer** [comment]
Well, that's... not optimal 🙃

We first need to be able to replicate it or at least need some confirmation what's the cause. Otherwise I don't think it can be fixed.

Thanks for your efforts so far, though! Will think about it some more.

**Comment by armenmargaryan** [comment]
I have news, that issue happened also on old version"threads": "0.8.1",  ..

Before slave.js issue happened i have noticed that my mysql cpu goes high because of high traffic, then after sometime i notices many slave.js was running again but already mysql at that moment cpu was normal.

I don't have mysql read write anything inside thread, instead i have in inside thread message part in main thread with setInterval loop which contineously read mysql data and triggers thread with send().

It seems to me mysql can't respond to message part requests
something there braking or wrong data is added to send() prams for thread
after that thread not normally starts and slave js was already brock

is this looks logical for you ?

**Comment by andywer** [comment]
Please try to upgrade to v1.0. It comes with a completely new API, but fixes a lot of the issues of v0.x.

Feel free to re-open if the issue occurs in v1.0 beta, too.
