### ISSUE TITLE
How debug threads.js with Visual studio code

### ISSUE THREAD

**Issue by thiensu5355** [andywer/threads.js#95]
I apply threads.js for Nodejs. It runs very well, but how i can apply  debug threads.js with Visual studio code

**Comment by victor0801x** [comment]
If your worker code in separate files, try enable `autoAttachChildProcesses` option
```js
// in .vscode/launch.json
        {
            "type": "node",
            "request": "launch",
            "name": "thread",
            "program": "${workspaceFolder}/main.js",
            "autoAttachChildProcesses": true
        }
```

**Comment by thiensu5355** [comment]
> Hey! Can't tell you actually, even though I'm using VS Code myself. Never figured out how that stupid debugger integration works... 😅
> 
> My suggestion: Just use [ndb](https://www.npmjs.com/package/ndb), launched from command line.

thank you, i will try it 😅

**Comment by thiensu5355** [comment]
> If your worker code in separate files, try enable `autoAttachChildProcesses` option
> 
> ```js
> // in .vscode/launch.json
>         {
>             "type": "node",
>             "request": "launch",
>             "name": "thread",
>             "program": "${workspaceFolder}/main.js",
>             "autoAttachChildProcesses": true
>         }
> ```
It doesn't work ^^. thank you. You know, for threads.js I think we should use `Console.log()` 😅

**Comment by victor0801x** [comment]
it works on me (but only at separated files, not inline)

**Comment by andywer** [comment]
Closing this issue for now, since I don't see an actionable right now.

If anyone finds a good solution to this, please share here 😉
